// NC County data for hyper-local SEO targeting
// All 100 North Carolina counties

export interface CountyData {
  slug: string;
  name: string;
  state: string;
  stateAbbr: string;
  countySeat: string;
  population: string;
  cities: string[];
  zipCodes: string[];
  description: string;
  roofingConsiderations: string[];
  popularMaterials: string[];
  avgRoofCost: { low: number; mid: number; high: number };
  climate: string;
  landmarks: string[];
  nearbyCounties: string[];
  region: string;
}

export const ncCounties: CountyData[] = [
  // CHARLOTTE METRO REGION (9 counties)
  {
    slug: 'mecklenburg-county-nc',
    name: 'Mecklenburg County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Charlotte',
    population: '1.1 million+',
    cities: ['charlotte-nc', 'huntersville-nc', 'cornelius-nc', 'davidson-nc', 'pineville-nc', 'matthews-nc', 'mint-hill-nc'],
    zipCodes: ['28202', '28203', '28204', '28205', '28206', '28207', '28208', '28209', '28210', '28211', '28212', '28213', '28214', '28215', '28216', '28217', '28226', '28227', '28262', '28269', '28270', '28273', '28277', '28278', '28031', '28036', '28078', '28105', '28134'],
    description: 'Mecklenburg County is the most populous county in North Carolina, home to Charlotte and its thriving suburbs. The county features diverse housing from historic Dilworth bungalows to modern Ballantyne estates.',
    roofingConsiderations: ['High humidity causing algae growth', 'Summer thunderstorms with hail', 'Tropical storm remnants', 'Urban heat island effects', 'HOA requirements in many subdivisions'],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Designer Shingles', 'Slate', 'TPO for commercial'],
    avgRoofCost: { low: 7500, mid: 14000, high: 28000 },
    climate: 'Humid subtropical with hot summers and mild winters',
    landmarks: ['Bank of America Stadium', 'Spectrum Center', 'Freedom Park', 'NASCAR Hall of Fame'],
    nearbyCounties: ['cabarrus-county-nc', 'gaston-county-nc', 'union-county-nc', 'iredell-county-nc', 'lincoln-county-nc'],
    region: 'Charlotte Metro'
  },
  {
    slug: 'cabarrus-county-nc',
    name: 'Cabarrus County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Concord',
    population: '225,000+',
    cities: ['concord-nc', 'kannapolis-nc', 'harrisburg-nc', 'midland-nc', 'mount-pleasant-nc'],
    zipCodes: ['28025', '28026', '28027', '28075', '28081', '28082', '28083', '28107', '28124'],
    description: 'Cabarrus County is known as the Speed Capital of the South, home to Charlotte Motor Speedway and rapid suburban growth from Charlotte.',
    roofingConsiderations: ['Speedway area noise and vibration', 'Rapid new construction', 'Mix of historic and modern homes', 'Summer storm damage', 'Growing HOA communities'],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Designer Shingles', 'Standing Seam Metal'],
    avgRoofCost: { low: 7000, mid: 13000, high: 24000 },
    climate: 'Humid subtropical',
    landmarks: ['Charlotte Motor Speedway', 'Concord Mills', 'Great Wolf Lodge'],
    nearbyCounties: ['mecklenburg-county-nc', 'rowan-county-nc', 'stanly-county-nc', 'union-county-nc'],
    region: 'Charlotte Metro'
  },
  {
    slug: 'gaston-county-nc',
    name: 'Gaston County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Gastonia',
    population: '230,000+',
    cities: ['gastonia-nc', 'belmont-nc', 'mount-holly-nc', 'lowell-nc', 'cramerton-nc', 'bessemer-city-nc', 'cherryville-nc', 'dallas-nc', 'stanley-nc', 'ranlo-nc', 'mcadenville-nc', 'high-shoals-nc'],
    zipCodes: ['28006', '28012', '28016', '28021', '28032', '28034', '28052', '28053', '28054', '28056', '28098', '28101', '28120'],
    description: 'Gaston County offers affordable housing west of Charlotte with mountain views. Historic textile towns are transforming into commuter suburbs with diverse roofing needs.',
    roofingConsiderations: ['Older textile-era homes', 'Mountain-influenced weather', 'Heavy rainfall', 'Tree debris from storms', 'Mix of rural and suburban'],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', '3-Tab Shingles', 'Standing Seam Metal'],
    avgRoofCost: { low: 6500, mid: 12000, high: 22000 },
    climate: 'Humid subtropical with mountain influence',
    landmarks: ['Crowders Mountain State Park', 'Daniel Stowe Botanical Garden', 'McAdenville Christmas Town'],
    nearbyCounties: ['mecklenburg-county-nc', 'lincoln-county-nc', 'cleveland-county-nc', 'york-county-sc'],
    region: 'Charlotte Metro'
  },
  {
    slug: 'union-county-nc',
    name: 'Union County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Monroe',
    population: '240,000+',
    cities: ['monroe-nc', 'indian-trail-nc', 'weddington-nc', 'waxhaw-nc', 'stallings-nc', 'marshville-nc', 'wingate-nc', 'hemby-bridge-nc'],
    zipCodes: ['28079', '28103', '28104', '28108', '28110', '28111', '28112', '28173', '28174'],
    description: 'Union County is one of the fastest-growing counties in NC, featuring upscale subdivisions in Weddington and Waxhaw with family-friendly communities.',
    roofingConsiderations: ['Premium home requirements', 'Strict HOA standards', 'New construction warranties', 'Large roof areas', 'Designer material demand'],
    popularMaterials: ['Designer Shingles', 'Architectural Shingles', 'Metal Roofing', 'Slate', 'Cedar Shakes'],
    avgRoofCost: { low: 8000, mid: 15000, high: 32000 },
    climate: 'Humid subtropical',
    landmarks: ['Cane Creek Park', 'Jesse Helms Center', 'Downtown Monroe'],
    nearbyCounties: ['mecklenburg-county-nc', 'cabarrus-county-nc', 'stanly-county-nc', 'anson-county-nc'],
    region: 'Charlotte Metro'
  },
  {
    slug: 'iredell-county-nc',
    name: 'Iredell County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Statesville',
    population: '185,000+',
    cities: ['mooresville-nc', 'statesville-nc', 'troutman-nc', 'lake-norman-nc'],
    zipCodes: ['28115', '28117', '28125', '28166', '28677', '28687'],
    description: 'Iredell County spans Lake Norman lakefront luxury to Statesville\'s historic downtown. Race City USA is home to NASCAR teams and Lowe\'s headquarters.',
    roofingConsiderations: ['Lake effect weather', 'Premium waterfront homes', 'NASCAR facility proximity', 'Mix of luxury and rural', 'Wind exposure near lake'],
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Standing Seam Metal', 'Slate', 'Designer Shingles'],
    avgRoofCost: { low: 7500, mid: 14500, high: 35000 },
    climate: 'Humid subtropical with lake influence',
    landmarks: ['Lake Norman', 'Lowe\'s Corporate HQ', 'NASCAR Technical Institute'],
    nearbyCounties: ['mecklenburg-county-nc', 'rowan-county-nc', 'catawba-county-nc', 'alexander-county-nc', 'davie-county-nc'],
    region: 'Charlotte Metro'
  },
  {
    slug: 'lincoln-county-nc',
    name: 'Lincoln County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Lincolnton',
    population: '88,000+',
    cities: ['lincolnton-nc', 'denver-nc', 'sherrills-ford-nc'],
    zipCodes: ['28037', '28080', '28092', '28150', '28168'],
    description: 'Lincoln County offers Lake Norman western shore living and small-town charm in Lincolnton. Growing bedroom community for Charlotte commuters.',
    roofingConsiderations: ['Lakefront humidity', 'Rural property access', 'Mix of old and new homes', 'Growing subdivisions', 'Agricultural area weather'],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Standing Seam Metal', '3-Tab Shingles'],
    avgRoofCost: { low: 6500, mid: 12500, high: 26000 },
    climate: 'Humid subtropical',
    landmarks: ['Lake Norman State Park', 'Historic Lincolnton', 'Bost Grist Mill'],
    nearbyCounties: ['gaston-county-nc', 'catawba-county-nc', 'iredell-county-nc', 'mecklenburg-county-nc'],
    region: 'Charlotte Metro'
  },
  {
    slug: 'rowan-county-nc',
    name: 'Rowan County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Salisbury',
    population: '145,000+',
    cities: ['salisbury-nc', 'china-grove-nc', 'landis-nc', 'rockwell-nc', 'granite-quarry-nc', 'spencer-nc'],
    zipCodes: ['28023', '28039', '28071', '28083', '28088', '28138', '28144', '28145', '28146', '28147'],
    description: 'Rowan County features historic Salisbury with Victorian architecture and growing I-85 corridor communities. Rich history meets suburban expansion.',
    roofingConsiderations: ['Historic preservation requirements', 'Victorian home complexity', 'I-85 corridor development', 'Older housing stock', 'Mixed urban/rural'],
    popularMaterials: ['Architectural Shingles', 'Slate', 'Metal Roofing', 'Cedar Shakes', 'Standing Seam Metal'],
    avgRoofCost: { low: 6000, mid: 11500, high: 24000 },
    climate: 'Humid subtropical',
    landmarks: ['Historic Downtown Salisbury', 'NC Transportation Museum', 'Dan Nicholas Park'],
    nearbyCounties: ['cabarrus-county-nc', 'iredell-county-nc', 'davidson-county-nc', 'stanly-county-nc', 'davie-county-nc'],
    region: 'Charlotte Metro'
  },
  {
    slug: 'stanly-county-nc',
    name: 'Stanly County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Albemarle',
    population: '63,000+',
    cities: ['locust-nc', 'stanfield-nc', 'oakboro-nc', 'midland-nc'],
    zipCodes: ['28001', '28002', '28007', '28071', '28097', '28107', '28127', '28128', '28129', '28137', '28138'],
    description: 'Stanly County offers affordable rural living east of Charlotte with Morrow Mountain State Park and Lake Tillery recreation.',
    roofingConsiderations: ['Rural property access', 'Agricultural buildings', 'Lake property considerations', 'Older farmhouses', 'Limited contractor availability'],
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', '3-Tab Shingles', 'Standing Seam Metal'],
    avgRoofCost: { low: 5500, mid: 10500, high: 20000 },
    climate: 'Humid subtropical',
    landmarks: ['Morrow Mountain State Park', 'Lake Tillery', 'Downtown Albemarle'],
    nearbyCounties: ['cabarrus-county-nc', 'union-county-nc', 'anson-county-nc', 'montgomery-county-nc', 'rowan-county-nc'],
    region: 'Charlotte Metro'
  },
  {
    slug: 'anson-county-nc',
    name: 'Anson County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Wadesboro',
    population: '24,000+',
    cities: [],
    zipCodes: ['28119', '28133', '28135', '28170'],
    description: 'Anson County is a rural county south of Charlotte with affordable housing and agricultural heritage. Growing as a distant Charlotte suburb.',
    roofingConsiderations: ['Rural access challenges', 'Older housing stock', 'Agricultural buildings', 'Limited local contractors', 'Budget-conscious market'],
    popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'],
    avgRoofCost: { low: 5000, mid: 9500, high: 18000 },
    climate: 'Humid subtropical',
    landmarks: ['Pee Dee National Wildlife Refuge', 'Historic Wadesboro'],
    nearbyCounties: ['union-county-nc', 'stanly-county-nc', 'richmond-county-nc', 'montgomery-county-nc'],
    region: 'Charlotte Metro'
  },

  // TRIANGLE REGION (8 counties)
  {
    slug: 'wake-county-nc',
    name: 'Wake County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Raleigh',
    population: '1.15 million+',
    cities: ['raleigh-nc'],
    zipCodes: ['27601', '27603', '27604', '27605', '27606', '27607', '27608', '27609', '27610', '27612', '27613', '27614', '27615', '27616', '27617'],
    description: 'Wake County is home to Raleigh, the state capital, and the Research Triangle. Fast-growing tech hub with diverse housing.',
    roofingConsiderations: ['Rapid growth construction', 'Tech corridor developments', 'Historic Raleigh homes', 'HOA communities', 'University area rentals'],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Designer Shingles', 'Standing Seam Metal'],
    avgRoofCost: { low: 7500, mid: 14000, high: 28000 },
    climate: 'Humid subtropical',
    landmarks: ['NC State University', 'State Capitol', 'Research Triangle Park'],
    nearbyCounties: ['durham-county-nc', 'orange-county-nc', 'chatham-county-nc', 'johnston-county-nc', 'franklin-county-nc'],
    region: 'Triangle'
  },
  {
    slug: 'durham-county-nc',
    name: 'Durham County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Durham',
    population: '330,000+',
    cities: ['durham-nc'],
    zipCodes: ['27701', '27703', '27704', '27705', '27706', '27707', '27708', '27709', '27710', '27712', '27713'],
    description: 'Durham County is the Bull City, home to Duke University and thriving downtown with historic tobacco warehouse conversions.',
    roofingConsiderations: ['Historic warehouse conversions', 'University area properties', 'Downtown flat roofs', 'Older neighborhoods', 'Rapid gentrification'],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'TPO', 'EPDM', 'Slate'],
    avgRoofCost: { low: 7500, mid: 14000, high: 28000 },
    climate: 'Humid subtropical',
    landmarks: ['Duke University', 'Durham Bulls Athletic Park', 'American Tobacco Campus'],
    nearbyCounties: ['wake-county-nc', 'orange-county-nc', 'chatham-county-nc', 'person-county-nc', 'granville-county-nc'],
    region: 'Triangle'
  },
  {
    slug: 'orange-county-nc',
    name: 'Orange County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Hillsborough',
    population: '150,000+',
    cities: [],
    zipCodes: ['27231', '27243', '27278', '27302', '27510', '27514', '27516', '27517'],
    description: 'Orange County is home to UNC Chapel Hill and historic Hillsborough. College town atmosphere with student rentals and upscale homes.',
    roofingConsiderations: ['University rental properties', 'Historic Hillsborough homes', 'Student housing turnover', 'Environmentally-conscious community', 'Older homes'],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Solar-ready roofing', 'Cedar Shakes'],
    avgRoofCost: { low: 7000, mid: 13500, high: 26000 },
    climate: 'Humid subtropical',
    landmarks: ['UNC Chapel Hill', 'Historic Hillsborough', 'Eno River State Park'],
    nearbyCounties: ['durham-county-nc', 'wake-county-nc', 'chatham-county-nc', 'alamance-county-nc', 'caswell-county-nc'],
    region: 'Triangle'
  },
  {
    slug: 'chatham-county-nc',
    name: 'Chatham County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Pittsboro',
    population: '80,000+',
    cities: [],
    zipCodes: ['27207', '27208', '27252', '27312', '27344', '27559'],
    description: 'Chatham County is rapidly growing between Raleigh and Greensboro. Pittsboro\'s charming downtown attracts new residents.',
    roofingConsiderations: ['Rural property access', 'New subdivision growth', 'Historic Pittsboro', 'Agricultural buildings', 'Vineyard properties'],
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Standing Seam Metal', '3-Tab Shingles'],
    avgRoofCost: { low: 6500, mid: 12500, high: 24000 },
    climate: 'Humid subtropical',
    landmarks: ['Jordan Lake', 'Fearrington Village', 'Historic Pittsboro'],
    nearbyCounties: ['wake-county-nc', 'durham-county-nc', 'orange-county-nc', 'lee-county-nc', 'moore-county-nc'],
    region: 'Triangle'
  },
  {
    slug: 'johnston-county-nc',
    name: 'Johnston County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Smithfield',
    population: '215,000+',
    cities: [],
    zipCodes: ['27520', '27524', '27526', '27527', '27529', '27542', '27576', '27577', '27592'],
    description: 'Johnston County is one of NC\'s fastest-growing counties, offering affordable housing southeast of Raleigh.',
    roofingConsiderations: ['Rapid new construction', 'Affordable housing market', 'Agricultural transitions', 'I-95 corridor growth', 'Rural and suburban mix'],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', '3-Tab Shingles', 'Standing Seam Metal'],
    avgRoofCost: { low: 6000, mid: 11500, high: 22000 },
    climate: 'Humid subtropical',
    landmarks: ['Ava Gardner Museum', 'Carolina Premium Outlets', 'Downtown Smithfield'],
    nearbyCounties: ['wake-county-nc', 'harnett-county-nc', 'sampson-county-nc', 'wayne-county-nc', 'wilson-county-nc'],
    region: 'Triangle'
  },
  {
    slug: 'franklin-county-nc',
    name: 'Franklin County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Louisburg',
    population: '70,000+',
    cities: [],
    zipCodes: ['27549', '27553', '27596', '27597'],
    description: 'Franklin County offers affordable rural living north of Raleigh with Falls Lake recreation and growing commuter communities.',
    roofingConsiderations: ['Rural property access', 'Lake property considerations', 'Older farmhouses', 'Growing subdivisions', 'Agricultural buildings'],
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', '3-Tab Shingles'],
    avgRoofCost: { low: 5500, mid: 10500, high: 20000 },
    climate: 'Humid subtropical',
    landmarks: ['Falls Lake', 'Louisburg College', 'Tar River'],
    nearbyCounties: ['wake-county-nc', 'granville-county-nc', 'vance-county-nc', 'nash-county-nc'],
    region: 'Triangle'
  },
  {
    slug: 'granville-county-nc',
    name: 'Granville County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Oxford',
    population: '62,000+',
    cities: [],
    zipCodes: ['27503', '27509', '27522', '27565', '27583'],
    description: 'Granville County is rural north of Durham with tobacco heritage and growing as a Triangle bedroom community.',
    roofingConsiderations: ['Historic tobacco barns', 'Rural access', 'Older housing stock', 'Agricultural properties', 'Limited contractors'],
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', '3-Tab Shingles'],
    avgRoofCost: { low: 5500, mid: 10000, high: 19000 },
    climate: 'Humid subtropical',
    landmarks: ['Historic Oxford', 'Kerr Lake', 'Lake Gaston'],
    nearbyCounties: ['durham-county-nc', 'wake-county-nc', 'franklin-county-nc', 'vance-county-nc', 'person-county-nc'],
    region: 'Triangle'
  },
  {
    slug: 'person-county-nc',
    name: 'Person County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Roxboro',
    population: '40,000+',
    cities: [],
    zipCodes: ['27343', '27541', '27572', '27573', '27574'],
    description: 'Person County is rural on the Virginia border with Hyco Lake recreation and affordable housing north of Durham.',
    roofingConsiderations: ['Rural access challenges', 'Lake property needs', 'Older tobacco-era homes', 'Limited local contractors', 'Budget-conscious market'],
    popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'],
    avgRoofCost: { low: 5000, mid: 9500, high: 18000 },
    climate: 'Humid subtropical',
    landmarks: ['Hyco Lake', 'Mayo Lake', 'Historic Roxboro'],
    nearbyCounties: ['durham-county-nc', 'orange-county-nc', 'granville-county-nc', 'caswell-county-nc'],
    region: 'Triangle'
  },

  // TRIAD REGION (12 counties)
  {
    slug: 'guilford-county-nc',
    name: 'Guilford County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Greensboro',
    population: '540,000+',
    cities: ['greensboro-nc'],
    zipCodes: ['27401', '27403', '27405', '27406', '27407', '27408', '27409', '27410', '27455'],
    description: 'Guilford County is the Triad\'s largest county, home to Greensboro and High Point. Furniture market capital with diverse housing.',
    roofingConsiderations: ['Historic districts', 'University properties', 'Furniture market buildings', 'Older neighborhoods', 'Commercial/industrial mix'],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'TPO', 'EPDM', 'Designer Shingles'],
    avgRoofCost: { low: 7000, mid: 13000, high: 26000 },
    climate: 'Humid subtropical',
    landmarks: ['Greensboro Coliseum', 'High Point Market', 'Guilford Courthouse'],
    nearbyCounties: ['forsyth-county-nc', 'randolph-county-nc', 'alamance-county-nc', 'rockingham-county-nc', 'davidson-county-nc'],
    region: 'Triad'
  },
  {
    slug: 'forsyth-county-nc',
    name: 'Forsyth County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Winston-Salem',
    population: '385,000+',
    cities: [],
    zipCodes: ['27101', '27103', '27104', '27105', '27106', '27107', '27109', '27127'],
    description: 'Forsyth County is home to Winston-Salem with historic Moravian heritage, Wake Forest University, and major healthcare industry.',
    roofingConsiderations: ['Historic Old Salem district', 'University properties', 'Medical campus roofing', 'Older tobacco industry homes', 'Urban renewal areas'],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate', 'Cedar Shakes', 'TPO'],
    avgRoofCost: { low: 7000, mid: 13000, high: 26000 },
    climate: 'Humid subtropical',
    landmarks: ['Old Salem', 'Wake Forest University', 'Reynolda House'],
    nearbyCounties: ['guilford-county-nc', 'davidson-county-nc', 'davie-county-nc', 'stokes-county-nc', 'yadkin-county-nc'],
    region: 'Triad'
  },
  {
    slug: 'davidson-county-nc',
    name: 'Davidson County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Lexington',
    population: '170,000+',
    cities: [],
    zipCodes: ['27292', '27295', '27299', '27360'],
    description: 'Davidson County is BBQ capital of NC with Lexington-style tradition. High Point Lake recreation and furniture manufacturing heritage.',
    roofingConsiderations: ['Manufacturing buildings', 'Older downtown properties', 'Lake area homes', 'Rural farming areas', 'Growing suburbs'],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', '3-Tab Shingles', 'Standing Seam Metal'],
    avgRoofCost: { low: 6000, mid: 11500, high: 22000 },
    climate: 'Humid subtropical',
    landmarks: ['High Point Lake', 'Lexington BBQ Festival', 'Historic Lexington'],
    nearbyCounties: ['forsyth-county-nc', 'guilford-county-nc', 'randolph-county-nc', 'rowan-county-nc', 'davie-county-nc'],
    region: 'Triad'
  },
  {
    slug: 'randolph-county-nc',
    name: 'Randolph County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Asheboro',
    population: '145,000+',
    cities: [],
    zipCodes: ['27203', '27204', '27205', '27263', '27298', '27316', '27317', '27341', '27350', '27370'],
    description: 'Randolph County is home to NC Zoo and pottery tradition. Mix of rural farming, manufacturing, and growing Triad suburbs.',
    roofingConsiderations: ['Rural access', 'Pottery/craft buildings', 'Agricultural structures', 'Mix of old and new', 'Zoo area properties'],
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', '3-Tab Shingles', 'Standing Seam Metal'],
    avgRoofCost: { low: 5500, mid: 11000, high: 21000 },
    climate: 'Humid subtropical',
    landmarks: ['NC Zoo', 'Seagrove Pottery', 'Uwharrie National Forest'],
    nearbyCounties: ['guilford-county-nc', 'davidson-county-nc', 'chatham-county-nc', 'moore-county-nc', 'montgomery-county-nc'],
    region: 'Triad'
  },
  {
    slug: 'rockingham-county-nc',
    name: 'Rockingham County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Wentworth',
    population: '90,000+',
    cities: [],
    zipCodes: ['27025', '27027', '27048', '27288', '27311', '27320', '27375'],
    description: 'Rockingham County is on the Virginia border with Dan River recreation and textile heritage communities.',
    roofingConsiderations: ['Older mill housing', 'Rural properties', 'River area humidity', 'Limited contractors', 'Budget-conscious market'],
    popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'],
    avgRoofCost: { low: 5000, mid: 10000, high: 19000 },
    climate: 'Humid subtropical',
    landmarks: ['Dan River', 'Chinqua-Penn Plantation', 'Madison-Mayodan'],
    nearbyCounties: ['guilford-county-nc', 'caswell-county-nc', 'stokes-county-nc'],
    region: 'Triad'
  },
  {
    slug: 'stokes-county-nc',
    name: 'Stokes County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Danbury',
    population: '45,000+',
    cities: [],
    zipCodes: ['27016', '27019', '27021', '27022', '27024', '27043', '27047', '27050', '27052'],
    description: 'Stokes County is scenic foothills county with Hanging Rock State Park and Pilot Mountain. Rural living near Winston-Salem.',
    roofingConsiderations: ['Mountain weather exposure', 'Rural access', 'Vacation homes', 'Older farmhouses', 'Limited contractors'],
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Standing Seam Metal'],
    avgRoofCost: { low: 5500, mid: 10500, high: 20000 },
    climate: 'Humid subtropical with mountain influence',
    landmarks: ['Hanging Rock State Park', 'Pilot Mountain', 'Dan River'],
    nearbyCounties: ['forsyth-county-nc', 'rockingham-county-nc', 'surry-county-nc', 'yadkin-county-nc'],
    region: 'Triad'
  },
  {
    slug: 'surry-county-nc',
    name: 'Surry County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Dobson',
    population: '71,000+',
    cities: [],
    zipCodes: ['27007', '27017', '27024', '27030', '27041', '27042', '27053', '28621', '28676'],
    description: 'Surry County is Andy Griffith\'s hometown with Mount Airy as Mayberry. Wine country and Pilot Mountain recreation.',
    roofingConsiderations: ['Historic Mount Airy downtown', 'Vineyard properties', 'Mountain exposure', 'Tourism properties', 'Older housing stock'],
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Standing Seam Metal', 'Cedar Shakes'],
    avgRoofCost: { low: 5500, mid: 10500, high: 21000 },
    climate: 'Humid subtropical with mountain influence',
    landmarks: ['Mount Airy (Mayberry)', 'Pilot Mountain', 'Yadkin Valley Wineries'],
    nearbyCounties: ['stokes-county-nc', 'yadkin-county-nc', 'wilkes-county-nc', 'alleghany-county-nc'],
    region: 'Triad'
  },
  {
    slug: 'yadkin-county-nc',
    name: 'Yadkin County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Yadkinville',
    population: '37,000+',
    cities: [],
    zipCodes: ['27006', '27011', '27014', '27018', '27020', '27023', '27028', '27040', '27055'],
    description: 'Yadkin County is heart of NC wine country with rolling hills and vineyards. Rural agricultural community near Winston-Salem.',
    roofingConsiderations: ['Vineyard buildings', 'Rural access', 'Agricultural structures', 'Wine tourism properties', 'Limited contractors'],
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', '3-Tab Shingles', 'Standing Seam Metal'],
    avgRoofCost: { low: 5000, mid: 10000, high: 19000 },
    climate: 'Humid subtropical',
    landmarks: ['Yadkin Valley Wine Trail', 'W. Kerr Scott Dam', 'Historic Yadkinville'],
    nearbyCounties: ['forsyth-county-nc', 'surry-county-nc', 'wilkes-county-nc', 'davie-county-nc', 'stokes-county-nc'],
    region: 'Triad'
  },
  {
    slug: 'davie-county-nc',
    name: 'Davie County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Mocksville',
    population: '43,000+',
    cities: [],
    zipCodes: ['27006', '27011', '27014', '27028'],
    description: 'Davie County is rural county between Winston-Salem and Charlotte. Growing bedroom community with agricultural heritage.',
    roofingConsiderations: ['Rural properties', 'Agricultural buildings', 'Growing subdivisions', 'Lake Norman proximity', 'Mix of old and new'],
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', '3-Tab Shingles'],
    avgRoofCost: { low: 5500, mid: 10500, high: 20000 },
    climate: 'Humid subtropical',
    landmarks: ['Historic Mocksville', 'Davie County wineries', 'Lake Norman access'],
    nearbyCounties: ['forsyth-county-nc', 'davidson-county-nc', 'iredell-county-nc', 'rowan-county-nc', 'yadkin-county-nc'],
    region: 'Triad'
  },
  {
    slug: 'alamance-county-nc',
    name: 'Alamance County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Graham',
    population: '165,000+',
    cities: [],
    zipCodes: ['27215', '27217', '27244', '27253', '27258', '27302', '27349'],
    description: 'Alamance County bridges the Triangle and Triad with Burlington as the hub. Outlet shopping and growing commuter communities.',
    roofingConsiderations: ['Outlet mall commercial', 'Historic Graham', 'Mill village housing', 'Growing I-85 corridor', 'Mix of urban and rural'],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'TPO', '3-Tab Shingles'],
    avgRoofCost: { low: 6000, mid: 11500, high: 22000 },
    climate: 'Humid subtropical',
    landmarks: ['Tanger Outlets', 'Alamance Battleground', 'Historic Graham'],
    nearbyCounties: ['guilford-county-nc', 'orange-county-nc', 'chatham-county-nc', 'randolph-county-nc', 'caswell-county-nc'],
    region: 'Triad'
  },
  {
    slug: 'caswell-county-nc',
    name: 'Caswell County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Yanceyville',
    population: '22,000+',
    cities: [],
    zipCodes: ['27291', '27305', '27311', '27326', '27358', '27375', '27379'],
    description: 'Caswell County is rural on the Virginia border with tobacco heritage and affordable land. Quiet countryside living.',
    roofingConsiderations: ['Rural access challenges', 'Older tobacco-era homes', 'Limited contractors', 'Agricultural buildings', 'Budget-conscious market'],
    popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'],
    avgRoofCost: { low: 4500, mid: 9000, high: 17000 },
    climate: 'Humid subtropical',
    landmarks: ['Historic Yanceyville', 'Caswell County Courthouse', 'Hyco Lake'],
    nearbyCounties: ['rockingham-county-nc', 'orange-county-nc', 'alamance-county-nc', 'person-county-nc'],
    region: 'Triad'
  },
  {
    slug: 'montgomery-county-nc',
    name: 'Montgomery County',
    state: 'North Carolina',
    stateAbbr: 'NC',
    countySeat: 'Troy',
    population: '27,000+',
    cities: [],
    zipCodes: ['27229', '27306', '27325', '27341', '27356', '27371'],
    description: 'Montgomery County is rural Uwharrie country with Lake Tillery and Badin Lake recreation. Affordable rural living.',
    roofingConsiderations: ['Lake property needs', 'Rural access', 'Older housing', 'Recreational cabins', 'Limited contractors'],
    popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'],
    avgRoofCost: { low: 5000, mid: 9500, high: 18000 },
    climate: 'Humid subtropical',
    landmarks: ['Uwharrie National Forest', 'Lake Tillery', 'Badin Lake'],
    nearbyCounties: ['randolph-county-nc', 'stanly-county-nc', 'moore-county-nc', 'richmond-county-nc', 'anson-county-nc'],
    region: 'Triad'
  },

  // COASTAL REGION (28 counties)
  { slug: 'new-hanover-county-nc', name: 'New Hanover County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Wilmington', population: '235,000+', cities: ['wilmington-nc'], zipCodes: ['28401', '28403', '28405', '28409', '28411', '28412'], description: 'New Hanover County is coastal NC hub with Wilmington, UNCW, and beaches.', roofingConsiderations: ['Hurricane exposure', 'Salt air corrosion', 'Coastal wind codes', 'Historic downtown', 'Beach property needs'], popularMaterials: ['Metal Roofing', 'Impact-Resistant Shingles', 'Standing Seam Metal', 'Tile'], avgRoofCost: { low: 8000, mid: 15000, high: 32000 }, climate: 'Humid subtropical coastal', landmarks: ['Wrightsville Beach', 'USS North Carolina', 'Historic Wilmington'], nearbyCounties: ['brunswick-county-nc', 'pender-county-nc'], region: 'Coastal' },
  { slug: 'brunswick-county-nc', name: 'Brunswick County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Bolivia', population: '145,000+', cities: [], zipCodes: ['28422', '28451', '28461', '28462', '28465', '28467', '28468', '28469', '28470'], description: 'Brunswick County is fastest-growing NC county with beach towns and golf communities.', roofingConsiderations: ['Hurricane zones', 'Beach property codes', 'Salt spray damage', 'Golf community standards', 'Rapid growth construction'], popularMaterials: ['Metal Roofing', 'Impact-Resistant Shingles', 'Standing Seam Metal'], avgRoofCost: { low: 7500, mid: 14500, high: 30000 }, climate: 'Humid subtropical coastal', landmarks: ['Ocean Isle Beach', 'Sunset Beach', 'Oak Island'], nearbyCounties: ['new-hanover-county-nc', 'columbus-county-nc'], region: 'Coastal' },
  { slug: 'pender-county-nc', name: 'Pender County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Burgaw', population: '65,000+', cities: [], zipCodes: ['28425', '28435', '28443', '28454', '28457', '28478'], description: 'Pender County includes Topsail Beach and growing Wilmington suburbs.', roofingConsiderations: ['Hurricane exposure', 'Beach property codes', 'Rural access', 'Growing subdivisions', 'Salt air damage'], popularMaterials: ['Metal Roofing', 'Impact-Resistant Shingles', 'Architectural Shingles'], avgRoofCost: { low: 7000, mid: 13500, high: 28000 }, climate: 'Humid subtropical coastal', landmarks: ['Topsail Beach', 'Surf City', 'Holly Shelter Game Land'], nearbyCounties: ['new-hanover-county-nc', 'onslow-county-nc', 'duplin-county-nc'], region: 'Coastal' },
  { slug: 'onslow-county-nc', name: 'Onslow County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Jacksonville', population: '200,000+', cities: [], zipCodes: ['28540', '28542', '28543', '28544', '28546', '28555', '28574', '28584'], description: 'Onslow County is home to Camp Lejeune with military housing and coastal living.', roofingConsiderations: ['Military housing standards', 'Hurricane damage common', 'Rapid turnover', 'Coastal building codes', 'Salt air corrosion'], popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Impact-Resistant Shingles'], avgRoofCost: { low: 6500, mid: 12500, high: 26000 }, climate: 'Humid subtropical coastal', landmarks: ['Camp Lejeune', 'Hammocks Beach State Park', 'Swansboro'], nearbyCounties: ['pender-county-nc', 'carteret-county-nc', 'jones-county-nc', 'duplin-county-nc'], region: 'Coastal' },
  { slug: 'carteret-county-nc', name: 'Carteret County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Beaufort', population: '70,000+', cities: [], zipCodes: ['28510', '28512', '28516', '28531', '28557', '28570', '28575', '28577', '28582', '28594'], description: 'Carteret County is Crystal Coast with historic Beaufort and Atlantic Beach.', roofingConsiderations: ['Barrier island exposure', 'Salt spray damage', 'Hurricane zones', 'Historic properties', 'Marine environment'], popularMaterials: ['Metal Roofing', 'Impact-Resistant Shingles', 'Standing Seam Metal'], avgRoofCost: { low: 7500, mid: 14000, high: 30000 }, climate: 'Humid subtropical coastal', landmarks: ['Cape Lookout', 'Atlantic Beach', 'Historic Beaufort'], nearbyCounties: ['onslow-county-nc', 'craven-county-nc', 'pamlico-county-nc'], region: 'Coastal' },
  { slug: 'craven-county-nc', name: 'Craven County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'New Bern', population: '100,000+', cities: [], zipCodes: ['28560', '28562', '28563', '28564', '28571', '28586'], description: 'Craven County features historic New Bern, birthplace of Pepsi and NC capital.', roofingConsiderations: ['Historic district requirements', 'River flooding', 'Hurricane damage', 'Military base proximity', 'Older housing stock'], popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate', 'Standing Seam Metal'], avgRoofCost: { low: 6500, mid: 12500, high: 26000 }, climate: 'Humid subtropical coastal', landmarks: ['Historic New Bern', 'Tryon Palace', 'Cherry Point Marine Base'], nearbyCounties: ['carteret-county-nc', 'pamlico-county-nc', 'jones-county-nc', 'lenoir-county-nc'], region: 'Coastal' },
  { slug: 'pamlico-county-nc', name: 'Pamlico County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Bayboro', population: '12,000+', cities: [], zipCodes: ['28509', '28515', '28529', '28537', '28552', '28556', '28571', '28583', '28587'], description: 'Pamlico County is rural coastal county on Pamlico Sound with fishing communities.', roofingConsiderations: ['Hurricane exposure', 'Flooding risk', 'Salt air damage', 'Remote access', 'Limited contractors'], popularMaterials: ['Metal Roofing', 'Architectural Shingles'], avgRoofCost: { low: 5500, mid: 11000, high: 22000 }, climate: 'Humid subtropical coastal', landmarks: ['Pamlico Sound', 'Oriental sailing village', 'Neuse River'], nearbyCounties: ['craven-county-nc', 'beaufort-county-nc', 'carteret-county-nc'], region: 'Coastal' },
  { slug: 'beaufort-county-nc', name: 'Beaufort County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Washington', population: '47,000+', cities: [], zipCodes: ['27808', '27817', '27821', '27826', '27834', '27860', '27865', '27871', '27889'], description: 'Beaufort County is on Pamlico River with historic Washington (original).', roofingConsiderations: ['River flooding', 'Hurricane exposure', 'Historic downtown', 'Rural access', 'Older homes'], popularMaterials: ['Metal Roofing', 'Architectural Shingles', '3-Tab Shingles'], avgRoofCost: { low: 5500, mid: 10500, high: 21000 }, climate: 'Humid subtropical coastal', landmarks: ['Historic Washington', 'Pamlico River', 'Goose Creek State Park'], nearbyCounties: ['pamlico-county-nc', 'pitt-county-nc', 'hyde-county-nc', 'martin-county-nc'], region: 'Coastal' },
  { slug: 'hyde-county-nc', name: 'Hyde County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Swan Quarter', population: '5,000+', cities: [], zipCodes: ['27820', '27824', '27836', '27860', '27885'], description: 'Hyde County is NC\'s least populous with Ocracoke Island and wildlife refuges.', roofingConsiderations: ['Extreme hurricane exposure', 'Remote island access', 'Salt air damage', 'Limited contractors', 'Ferry-dependent areas'], popularMaterials: ['Metal Roofing', 'Impact-Resistant Shingles'], avgRoofCost: { low: 7000, mid: 14000, high: 28000 }, climate: 'Humid subtropical coastal', landmarks: ['Ocracoke Island', 'Mattamuskeet Lake', 'Swan Quarter ferry'], nearbyCounties: ['beaufort-county-nc', 'dare-county-nc', 'tyrrell-county-nc'], region: 'Coastal' },
  { slug: 'dare-county-nc', name: 'Dare County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Manteo', population: '38,000+', cities: [], zipCodes: ['27915', '27920', '27936', '27948', '27953', '27954', '27959', '27968', '27978', '27981'], description: 'Dare County is Outer Banks with Kitty Hawk, Kill Devil Hills, and Nags Head.', roofingConsiderations: ['Extreme hurricane exposure', 'Salt spray corrosion', 'Barrier island codes', 'Vacation rental standards', 'Wind uplift requirements'], popularMaterials: ['Metal Roofing', 'Impact-Resistant Shingles', 'Standing Seam Metal', 'Tile'], avgRoofCost: { low: 9000, mid: 17000, high: 38000 }, climate: 'Humid subtropical coastal', landmarks: ['Wright Brothers Memorial', 'Jockey\'s Ridge', 'Roanoke Island'], nearbyCounties: ['currituck-county-nc', 'hyde-county-nc', 'tyrrell-county-nc'], region: 'Coastal' },
  { slug: 'currituck-county-nc', name: 'Currituck County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Currituck', population: '28,000+', cities: [], zipCodes: ['27917', '27923', '27927', '27929', '27939', '27947', '27950', '27958', '27966'], description: 'Currituck County includes Corolla wild horses and luxury Outer Banks homes.', roofingConsiderations: ['Extreme wind exposure', 'Salt air damage', 'Premium home standards', '4WD access areas', 'Hurricane codes'], popularMaterials: ['Metal Roofing', 'Impact-Resistant Shingles', 'Standing Seam Metal'], avgRoofCost: { low: 9000, mid: 17000, high: 40000 }, climate: 'Humid subtropical coastal', landmarks: ['Corolla wild horses', 'Currituck Lighthouse', 'Outer Banks beaches'], nearbyCounties: ['dare-county-nc', 'camden-county-nc'], region: 'Coastal' },
  { slug: 'camden-county-nc', name: 'Camden County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Camden', population: '11,000+', cities: [], zipCodes: ['27921', '27976'], description: 'Camden County is rural northeastern county near Virginia border.', roofingConsiderations: ['Rural access', 'Coastal proximity', 'Older housing', 'Limited contractors', 'Agricultural buildings'], popularMaterials: ['Metal Roofing', 'Architectural Shingles', '3-Tab Shingles'], avgRoofCost: { low: 5000, mid: 10000, high: 19000 }, climate: 'Humid subtropical', landmarks: ['Dismal Swamp Canal', 'Historic Camden Courthouse'], nearbyCounties: ['currituck-county-nc', 'pasquotank-county-nc', 'gates-county-nc'], region: 'Coastal' },
  { slug: 'pasquotank-county-nc', name: 'Pasquotank County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Elizabeth City', population: '40,000+', cities: [], zipCodes: ['27906', '27907', '27909'], description: 'Pasquotank County features Elizabeth City with Coast Guard base.', roofingConsiderations: ['Coast Guard base standards', 'Historic downtown', 'Coastal humidity', 'River flooding', 'Older housing stock'], popularMaterials: ['Architectural Shingles', 'Metal Roofing', '3-Tab Shingles'], avgRoofCost: { low: 5500, mid: 10500, high: 21000 }, climate: 'Humid subtropical', landmarks: ['Elizabeth City State University', 'USCG Base', 'Pasquotank River'], nearbyCounties: ['camden-county-nc', 'perquimans-county-nc', 'chowan-county-nc'], region: 'Coastal' },
  { slug: 'perquimans-county-nc', name: 'Perquimans County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Hertford', population: '13,500+', cities: [], zipCodes: ['27930', '27944'], description: 'Perquimans County is small rural county with historic Hertford.', roofingConsiderations: ['Rural access', 'Historic properties', 'Older housing', 'Limited contractors', 'Agricultural buildings'], popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'], avgRoofCost: { low: 5000, mid: 9500, high: 18000 }, climate: 'Humid subtropical', landmarks: ['Historic Hertford', 'Perquimans River', 'Newbold-White House'], nearbyCounties: ['pasquotank-county-nc', 'chowan-county-nc', 'gates-county-nc'], region: 'Coastal' },
  { slug: 'chowan-county-nc', name: 'Chowan County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Edenton', population: '14,000+', cities: [], zipCodes: ['27932', '27980'], description: 'Chowan County has historic Edenton, one of NC\'s oldest towns.', roofingConsiderations: ['Historic district codes', 'Colonial-era homes', 'Waterfront properties', 'Older housing stock', 'Preservation requirements'], popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate', 'Cedar Shakes'], avgRoofCost: { low: 5500, mid: 11000, high: 24000 }, climate: 'Humid subtropical', landmarks: ['Historic Edenton', 'Cupola House', 'Albemarle Sound'], nearbyCounties: ['pasquotank-county-nc', 'perquimans-county-nc', 'gates-county-nc', 'bertie-county-nc'], region: 'Coastal' },
  { slug: 'gates-county-nc', name: 'Gates County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Gatesville', population: '11,500+', cities: [], zipCodes: ['27926', '27935', '27937', '27938', '27979'], description: 'Gates County is rural northeastern county at Virginia border.', roofingConsiderations: ['Rural access', 'Older housing', 'Limited contractors', 'Agricultural buildings', 'Budget-conscious market'], popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'], avgRoofCost: { low: 4500, mid: 9000, high: 17000 }, climate: 'Humid subtropical', landmarks: ['Merchants Millpond State Park', 'Chowan River', 'Historic Gatesville'], nearbyCounties: ['chowan-county-nc', 'hertford-county-nc', 'perquimans-county-nc', 'camden-county-nc'], region: 'Coastal' },
  { slug: 'hertford-county-nc', name: 'Hertford County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Winton', population: '24,000+', cities: [], zipCodes: ['27818', '27831', '27842', '27855', '27874', '27891', '27897'], description: 'Hertford County is rural northeastern NC with Chowan River access.', roofingConsiderations: ['Rural access', 'Older housing', 'River area humidity', 'Limited contractors', 'Agricultural buildings'], popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'], avgRoofCost: { low: 4500, mid: 9000, high: 17000 }, climate: 'Humid subtropical', landmarks: ['Chowan River', 'Historic Murfreesboro', 'Meherrin River'], nearbyCounties: ['gates-county-nc', 'bertie-county-nc', 'northampton-county-nc'], region: 'Coastal' },
  { slug: 'bertie-county-nc', name: 'Bertie County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Windsor', population: '19,000+', cities: [], zipCodes: ['27810', '27818', '27830', '27869', '27892', '27897'], description: 'Bertie County is rural county with Roanoke River and agricultural heritage.', roofingConsiderations: ['Rural access', 'River flooding', 'Older housing', 'Limited contractors', 'Agricultural buildings'], popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'], avgRoofCost: { low: 4500, mid: 9000, high: 17000 }, climate: 'Humid subtropical', landmarks: ['Roanoke River', 'Historic Windsor', 'Hope Plantation'], nearbyCounties: ['hertford-county-nc', 'martin-county-nc', 'chowan-county-nc', 'washington-county-nc'], region: 'Coastal' },
  { slug: 'martin-county-nc', name: 'Martin County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Williamston', population: '22,000+', cities: [], zipCodes: ['27809', '27843', '27845', '27857', '27871', '27892'], description: 'Martin County is rural eastern NC with Roanoke River recreation.', roofingConsiderations: ['Rural access', 'River flooding', 'Older housing', 'Limited contractors', 'Agricultural buildings'], popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'], avgRoofCost: { low: 4500, mid: 9000, high: 17000 }, climate: 'Humid subtropical', landmarks: ['Roanoke River', 'Historic Williamston', 'Senator Bob Martin Agricultural Center'], nearbyCounties: ['bertie-county-nc', 'beaufort-county-nc', 'pitt-county-nc', 'edgecombe-county-nc'], region: 'Coastal' },
  { slug: 'washington-county-nc', name: 'Washington County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Plymouth', population: '12,000+', cities: [], zipCodes: ['27860', '27925', '27962'], description: 'Washington County is rural with Roanoke River and Pocosin Lakes refuge.', roofingConsiderations: ['Rural access', 'Flooding risk', 'Limited contractors', 'Older housing', 'Agricultural buildings'], popularMaterials: ['Metal Roofing', '3-Tab Shingles'], avgRoofCost: { low: 4500, mid: 9000, high: 17000 }, climate: 'Humid subtropical', landmarks: ['Pocosin Lakes Wildlife Refuge', 'Historic Plymouth', 'Roanoke River'], nearbyCounties: ['bertie-county-nc', 'tyrrell-county-nc', 'beaufort-county-nc'], region: 'Coastal' },
  { slug: 'tyrrell-county-nc', name: 'Tyrrell County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Columbia', population: '4,000+', cities: [], zipCodes: ['27925'], description: 'Tyrrell County is one of NC\'s smallest with Scuppernong River and wildlife.', roofingConsiderations: ['Remote access', 'Flooding risk', 'Limited contractors', 'Older housing', 'Budget market'], popularMaterials: ['Metal Roofing', '3-Tab Shingles'], avgRoofCost: { low: 4500, mid: 9000, high: 17000 }, climate: 'Humid subtropical', landmarks: ['Pocosin Lakes', 'Scuppernong River', 'Columbia Waterfront'], nearbyCounties: ['washington-county-nc', 'hyde-county-nc', 'dare-county-nc'], region: 'Coastal' },
  { slug: 'pitt-county-nc', name: 'Pitt County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Greenville', population: '180,000+', cities: [], zipCodes: ['27833', '27834', '27835', '27836', '27858', '27834'], description: 'Pitt County features Greenville with ECU and Vidant Medical Center.', roofingConsiderations: ['University housing', 'Medical campus roofing', 'Historic areas', 'Growing suburbs', 'Mix of rentals and homes'], popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'TPO', 'EPDM'], avgRoofCost: { low: 6000, mid: 11500, high: 23000 }, climate: 'Humid subtropical', landmarks: ['East Carolina University', 'Vidant Medical Center', 'Greenville Convention Center'], nearbyCounties: ['beaufort-county-nc', 'martin-county-nc', 'edgecombe-county-nc', 'greene-county-nc', 'lenoir-county-nc'], region: 'Coastal' },
  { slug: 'greene-county-nc', name: 'Greene County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Snow Hill', population: '20,000+', cities: [], zipCodes: ['28530', '28538', '28551', '28580'], description: 'Greene County is rural agricultural county with small-town charm.', roofingConsiderations: ['Rural access', 'Agricultural buildings', 'Older housing', 'Limited contractors', 'Budget market'], popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'], avgRoofCost: { low: 5000, mid: 9500, high: 18000 }, climate: 'Humid subtropical', landmarks: ['Contentnea Creek', 'Historic Snow Hill'], nearbyCounties: ['pitt-county-nc', 'lenoir-county-nc', 'wayne-county-nc'], region: 'Coastal' },
  { slug: 'lenoir-county-nc', name: 'Lenoir County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Kinston', population: '55,000+', cities: [], zipCodes: ['28501', '28502', '28504', '28525', '28526'], description: 'Lenoir County features Kinston with BBQ culture and minor league baseball.', roofingConsiderations: ['Historic downtown', 'Older housing stock', 'Industrial buildings', 'River flooding', 'Mix of urban and rural'], popularMaterials: ['Architectural Shingles', 'Metal Roofing', '3-Tab Shingles'], avgRoofCost: { low: 5500, mid: 10500, high: 20000 }, climate: 'Humid subtropical', landmarks: ['CSS Neuse', 'Kinston Indians ballpark', 'Mother Earth Brewing'], nearbyCounties: ['pitt-county-nc', 'craven-county-nc', 'jones-county-nc', 'greene-county-nc', 'wayne-county-nc'], region: 'Coastal' },
  { slug: 'wayne-county-nc', name: 'Wayne County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Goldsboro', population: '125,000+', cities: [], zipCodes: ['27530', '27531', '27533', '27534', '28333', '28365', '28578'], description: 'Wayne County has Seymour Johnson Air Force Base and growing Goldsboro.', roofingConsiderations: ['Air Force base standards', 'Military housing', 'Historic Goldsboro', 'Industrial buildings', 'Agricultural area'], popularMaterials: ['Architectural Shingles', 'Metal Roofing', '3-Tab Shingles', 'TPO'], avgRoofCost: { low: 5500, mid: 11000, high: 22000 }, climate: 'Humid subtropical', landmarks: ['Seymour Johnson AFB', 'Historic Downtown Goldsboro', 'Cliffs of the Neuse'], nearbyCounties: ['johnston-county-nc', 'lenoir-county-nc', 'greene-county-nc', 'sampson-county-nc', 'duplin-county-nc'], region: 'Coastal' },
  { slug: 'duplin-county-nc', name: 'Duplin County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Kenansville', population: '59,000+', cities: [], zipCodes: ['28325', '28340', '28349', '28398', '28441', '28453', '28458', '28464', '28466'], description: 'Duplin County is agricultural with wine country and Duplin Winery.', roofingConsiderations: ['Agricultural buildings', 'Winery properties', 'Rural access', 'Older housing', 'Limited contractors'], popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'], avgRoofCost: { low: 5000, mid: 10000, high: 19000 }, climate: 'Humid subtropical', landmarks: ['Duplin Winery', 'Liberty Hall', 'Kenansville'], nearbyCounties: ['wayne-county-nc', 'sampson-county-nc', 'pender-county-nc', 'onslow-county-nc', 'lenoir-county-nc'], region: 'Coastal' },
  { slug: 'sampson-county-nc', name: 'Sampson County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Clinton', population: '63,000+', cities: [], zipCodes: ['28320', '28328', '28334', '28382', '28393', '28399', '28441'], description: 'Sampson County is large agricultural county in southeastern NC.', roofingConsiderations: ['Agricultural buildings', 'Rural access', 'Older housing', 'Limited contractors', 'Budget market'], popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'], avgRoofCost: { low: 5000, mid: 9500, high: 18000 }, climate: 'Humid subtropical', landmarks: ['Sampson County Expo Center', 'Downtown Clinton'], nearbyCounties: ['johnston-county-nc', 'wayne-county-nc', 'duplin-county-nc', 'bladen-county-nc', 'cumberland-county-nc'], region: 'Coastal' },
  { slug: 'bladen-county-nc', name: 'Bladen County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Elizabethtown', population: '32,000+', cities: [], zipCodes: ['28320', '28337', '28399', '28433', '28434', '28439', '28442', '28472'], description: 'Bladen County is rural with White Lake and Bladen Lakes State Forest.', roofingConsiderations: ['Lake properties', 'Rural access', 'Older housing', 'Limited contractors', 'Agricultural buildings'], popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'], avgRoofCost: { low: 5000, mid: 9500, high: 18000 }, climate: 'Humid subtropical', landmarks: ['White Lake', 'Bladen Lakes State Forest', 'Jones Lake'], nearbyCounties: ['sampson-county-nc', 'cumberland-county-nc', 'columbus-county-nc', 'robeson-county-nc', 'pender-county-nc'], region: 'Coastal' },
  { slug: 'jones-county-nc', name: 'Jones County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Trenton', population: '9,500+', cities: [], zipCodes: ['28523', '28526', '28560', '28585'], description: 'Jones County is NC\'s second-smallest with rural farms and forests.', roofingConsiderations: ['Rural access', 'Older housing', 'Limited contractors', 'Agricultural buildings', 'Budget market'], popularMaterials: ['Metal Roofing', '3-Tab Shingles'], avgRoofCost: { low: 4500, mid: 9000, high: 17000 }, climate: 'Humid subtropical', landmarks: ['Croatan National Forest', 'Trent River'], nearbyCounties: ['craven-county-nc', 'onslow-county-nc', 'lenoir-county-nc'], region: 'Coastal' },

  // SANDHILLS/SOUTHERN PIEDMONT REGION (14 counties)
  { slug: 'cumberland-county-nc', name: 'Cumberland County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Fayetteville', population: '335,000+', cities: [], zipCodes: ['28301', '28303', '28304', '28305', '28306', '28307', '28308', '28311', '28312', '28314'], description: 'Cumberland County is home to Fort Bragg (now Fort Liberty), the largest military base in the US.', roofingConsiderations: ['Military housing turnover', 'Base standards', 'Rapid construction', 'Mix of rentals', 'Hurricane exposure'], popularMaterials: ['Architectural Shingles', 'Metal Roofing', '3-Tab Shingles', 'TPO'], avgRoofCost: { low: 6000, mid: 11500, high: 23000 }, climate: 'Humid subtropical', landmarks: ['Fort Liberty', 'Cape Fear River', 'Fayetteville VA Medical Center'], nearbyCounties: ['harnett-county-nc', 'hoke-county-nc', 'sampson-county-nc', 'bladen-county-nc', 'robeson-county-nc'], region: 'Sandhills' },
  { slug: 'hoke-county-nc', name: 'Hoke County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Raeford', population: '55,000+', cities: [], zipCodes: ['28376'], description: 'Hoke County is one of NC\'s fastest-growing counties near Fort Liberty.', roofingConsiderations: ['Rapid growth', 'Military influence', 'New construction', 'Sandhills terrain', 'Growing subdivisions'], popularMaterials: ['Architectural Shingles', 'Metal Roofing', '3-Tab Shingles'], avgRoofCost: { low: 5500, mid: 10500, high: 21000 }, climate: 'Humid subtropical', landmarks: ['Fort Liberty', 'Raeford', 'Sandhills Game Land'], nearbyCounties: ['cumberland-county-nc', 'moore-county-nc', 'scotland-county-nc', 'robeson-county-nc'], region: 'Sandhills' },
  { slug: 'moore-county-nc', name: 'Moore County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Carthage', population: '100,000+', cities: [], zipCodes: ['27281', '28315', '28326', '28327', '28373', '28374', '28387', '28388'], description: 'Moore County is golf capital of the US with Pinehurst and Southern Pines.', roofingConsiderations: ['Premium golf community standards', 'HOA requirements', 'Upscale residential', 'Sandy soil challenges', 'Resort properties'], popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Designer Shingles', 'Cedar Shakes', 'Slate'], avgRoofCost: { low: 7500, mid: 14500, high: 32000 }, climate: 'Humid subtropical', landmarks: ['Pinehurst Resort', 'Southern Pines', 'Sandhills'], nearbyCounties: ['chatham-county-nc', 'randolph-county-nc', 'montgomery-county-nc', 'hoke-county-nc', 'lee-county-nc', 'richmond-county-nc'], region: 'Sandhills' },
  { slug: 'scotland-county-nc', name: 'Scotland County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Laurinburg', population: '35,000+', cities: [], zipCodes: ['28352', '28353', '28364'], description: 'Scotland County is rural Sandhills county with St. Andrews University.', roofingConsiderations: ['Rural access', 'Older housing', 'University properties', 'Limited contractors', 'Budget market'], popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'], avgRoofCost: { low: 5000, mid: 9500, high: 18000 }, climate: 'Humid subtropical', landmarks: ['St. Andrews University', 'John Blue House', 'Laurinburg'], nearbyCounties: ['hoke-county-nc', 'richmond-county-nc', 'robeson-county-nc'], region: 'Sandhills' },
  { slug: 'richmond-county-nc', name: 'Richmond County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Rockingham', population: '44,000+', cities: [], zipCodes: ['28345', '28347', '28379', '28380'], description: 'Richmond County is Sandhills county with Rockingham Speedway history.', roofingConsiderations: ['Rural properties', 'Older housing', 'Industrial buildings', 'Limited contractors', 'Budget market'], popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'], avgRoofCost: { low: 5000, mid: 9500, high: 18000 }, climate: 'Humid subtropical', landmarks: ['Rockingham Dragway', 'Historic Rockingham', 'Sandhills'],nearbyCounties: ['anson-county-nc', 'montgomery-county-nc', 'moore-county-nc', 'scotland-county-nc'], region: 'Sandhills' },
  { slug: 'harnett-county-nc', name: 'Harnett County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Lillington', population: '135,000+', cities: [], zipCodes: ['27501', '27505', '27546', '28323', '28326', '28334', '28339', '28356'], description: 'Harnett County is fast-growing between Raleigh and Fayetteville.', roofingConsiderations: ['Rapid new construction', 'Mix of rural and suburban', 'Military proximity', 'Growing HOA communities', 'Affordable housing market'], popularMaterials: ['Architectural Shingles', 'Metal Roofing', '3-Tab Shingles'], avgRoofCost: { low: 5500, mid: 11000, high: 22000 }, climate: 'Humid subtropical', landmarks: ['Raven Rock State Park', 'Downtown Lillington', 'Campbell University'],nearbyCounties: ['johnston-county-nc', 'wake-county-nc', 'cumberland-county-nc', 'lee-county-nc', 'chatham-county-nc'], region: 'Sandhills' },
  { slug: 'lee-county-nc', name: 'Lee County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Sanford', population: '63,000+', cities: [], zipCodes: ['27330', '27332'], description: 'Lee County features Sanford as brick capital with new manufacturing growth.', roofingConsiderations: ['Industrial buildings', 'Mix of old and new', 'Growing manufacturing', 'Rural areas', 'Affordable housing'], popularMaterials: ['Architectural Shingles', 'Metal Roofing', '3-Tab Shingles', 'TPO'], avgRoofCost: { low: 5500, mid: 10500, high: 21000 }, climate: 'Humid subtropical', landmarks: ['Historic Downtown Sanford', 'Cape Fear River', 'Railroad House'],nearbyCounties: ['chatham-county-nc', 'harnett-county-nc', 'moore-county-nc'], region: 'Sandhills' },
  { slug: 'columbus-county-nc', name: 'Columbus County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Whiteville', population: '55,000+', cities: [], zipCodes: ['28430', '28431', '28432', '28433', '28436', '28438', '28439', '28442', '28450', '28455', '28456', '28463', '28472'], description: 'Columbus County is rural southern NC with Lake Waccamaw natural wonder.', roofingConsiderations: ['Rural access', 'Hurricane exposure', 'Older housing', 'Lake properties', 'Limited contractors'], popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'], avgRoofCost: { low: 5000, mid: 9500, high: 18000 }, climate: 'Humid subtropical', landmarks: ['Lake Waccamaw', 'Historic Whiteville', 'Green Swamp'],nearbyCounties: ['bladen-county-nc', 'brunswick-county-nc', 'robeson-county-nc'], region: 'Sandhills' },
  { slug: 'robeson-county-nc', name: 'Robeson County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Lumberton', population: '130,000+', cities: [], zipCodes: ['28340', '28358', '28359', '28360', '28362', '28369', '28372', '28377', '28383', '28384', '28385', '28386', '28391', '28392'], description: 'Robeson County is NC\'s largest by area with Lumbee tribal lands.', roofingConsiderations: ['I-95 corridor', 'Rural properties', 'Flooding history', 'Mix of housing ages', 'Limited contractors'], popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'], avgRoofCost: { low: 5000, mid: 9500, high: 18000 }, climate: 'Humid subtropical', landmarks: ['Lumber River', 'Strike at the Wind', 'Lumberton'],nearbyCounties: ['cumberland-county-nc', 'hoke-county-nc', 'scotland-county-nc', 'bladen-county-nc', 'columbus-county-nc'], region: 'Sandhills' },
  { slug: 'edgecombe-county-nc', name: 'Edgecombe County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Tarboro', population: '52,000+', cities: [], zipCodes: ['27801', '27816', '27819', '27823', '27829', '27846', '27852', '27856', '27882', '27886'], description: 'Edgecombe County features historic Tarboro with tobacco heritage.', roofingConsiderations: ['Historic downtown', 'Older housing stock', 'Flooding risk', 'Rural properties', 'Limited contractors'], popularMaterials: ['Metal Roofing', 'Architectural Shingles', '3-Tab Shingles'], avgRoofCost: { low: 5000, mid: 9500, high: 18000 }, climate: 'Humid subtropical', landmarks: ['Historic Tarboro', 'Tar River', 'Blount-Bridgers House'],nearbyCounties: ['nash-county-nc', 'wilson-county-nc', 'pitt-county-nc', 'martin-county-nc', 'halifax-county-nc'], region: 'Sandhills' },
  { slug: 'nash-county-nc', name: 'Nash County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Nashville', population: '95,000+', cities: [], zipCodes: ['27801', '27803', '27804', '27806', '27809', '27822', '27856', '27878', '27882', '27893'], description: 'Nash County includes Rocky Mount shared with Edgecombe County.', roofingConsiderations: ['Twin cities area', 'Mix of urban and rural', 'Older downtown areas', 'Growing suburbs', 'Industrial properties'], popularMaterials: ['Architectural Shingles', 'Metal Roofing', '3-Tab Shingles'], avgRoofCost: { low: 5500, mid: 10500, high: 20000 }, climate: 'Humid subtropical', landmarks: ['Rocky Mount Mills', 'Nashville historic district', 'Tar River'],nearbyCounties: ['edgecombe-county-nc', 'wilson-county-nc', 'franklin-county-nc', 'halifax-county-nc'], region: 'Sandhills' },
  { slug: 'wilson-county-nc', name: 'Wilson County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Wilson', population: '82,000+', cities: [], zipCodes: ['27822', '27856', '27863', '27880', '27893', '27894', '27895', '27896'], description: 'Wilson County is tobacco heritage area with Vollis Simpson Whirligigs.', roofingConsiderations: ['Historic downtown', 'Tobacco warehouse conversions', 'Older housing', 'Rural properties', 'Mix of old and new'], popularMaterials: ['Architectural Shingles', 'Metal Roofing', '3-Tab Shingles'], avgRoofCost: { low: 5500, mid: 10500, high: 20000 }, climate: 'Humid subtropical', landmarks: ['Whirligig Park', 'Downtown Wilson', 'Boykin historic district'],nearbyCounties: ['nash-county-nc', 'johnston-county-nc', 'wayne-county-nc', 'pitt-county-nc', 'edgecombe-county-nc', 'greene-county-nc'], region: 'Sandhills' },
  { slug: 'halifax-county-nc', name: 'Halifax County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Halifax', population: '50,000+', cities: [], zipCodes: ['27839', '27843', '27850', '27853', '27870', '27874', '27890'], description: 'Halifax County is historic site of NC independence declaration.', roofingConsiderations: ['Historic properties', 'Rural access', 'Older housing', 'Limited contractors', 'Budget market'], popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'], avgRoofCost: { low: 4500, mid: 9000, high: 17000 }, climate: 'Humid subtropical', landmarks: ['Historic Halifax', 'Roanoke Canal Museum', 'Lake Gaston'],nearbyCounties: ['northampton-county-nc', 'nash-county-nc', 'edgecombe-county-nc', 'warren-county-nc'], region: 'Sandhills' },
  { slug: 'northampton-county-nc', name: 'Northampton County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Jackson', population: '19,000+', cities: [], zipCodes: ['27818', '27831', '27839', '27842', '27845', '27855', '27866', '27870', '27872', '27876'], description: 'Northampton County is rural VA border county with Lake Gaston recreation.', roofingConsiderations: ['Lake properties', 'Rural access', 'Older housing', 'Limited contractors', 'Budget market'], popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'], avgRoofCost: { low: 4500, mid: 9000, high: 17000 }, climate: 'Humid subtropical', landmarks: ['Lake Gaston', 'Historic Jackson', 'Roanoke River'],nearbyCounties: ['halifax-county-nc', 'hertford-county-nc', 'bertie-county-nc'], region: 'Sandhills' },
  { slug: 'vance-county-nc', name: 'Vance County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Henderson', population: '44,000+', cities: [], zipCodes: ['27507', '27537', '27544', '27556', '27565'], description: 'Vance County features Kerr Lake recreation and Henderson manufacturing.', roofingConsiderations: ['Lake properties', 'Industrial buildings', 'Older housing', 'Mix of rural and urban', 'Growing suburbs'], popularMaterials: ['Architectural Shingles', 'Metal Roofing', '3-Tab Shingles'], avgRoofCost: { low: 5000, mid: 10000, high: 19000 }, climate: 'Humid subtropical', landmarks: ['Kerr Lake', 'Historic Henderson', 'Satterwhite Point'],nearbyCounties: ['granville-county-nc', 'franklin-county-nc', 'warren-county-nc'], region: 'Sandhills' },
  { slug: 'warren-county-nc', name: 'Warren County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Warrenton', population: '19,000+', cities: [], zipCodes: ['27544', '27551', '27556', '27563', '27570', '27589'], description: 'Warren County is rural with Lake Gaston and historic Warrenton.', roofingConsiderations: ['Lake properties', 'Historic homes', 'Rural access', 'Limited contractors', 'Budget market'], popularMaterials: ['Metal Roofing', '3-Tab Shingles', 'Architectural Shingles'], avgRoofCost: { low: 4500, mid: 9000, high: 17000 }, climate: 'Humid subtropical', landmarks: ['Lake Gaston', 'Historic Warrenton', 'John Graham House'],nearbyCounties: ['vance-county-nc', 'halifax-county-nc', 'franklin-county-nc', 'granville-county-nc'], region: 'Sandhills' },

  // WESTERN NC / MOUNTAINS REGION (25 counties)
  { slug: 'buncombe-county-nc', name: 'Buncombe County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Asheville', population: '270,000+', cities: ['asheville-nc'], zipCodes: ['28701', '28704', '28709', '28711', '28715', '28730', '28748', '28778', '28787', '28801', '28803', '28804', '28805', '28806'], description: 'Buncombe County is mountain hub with Asheville arts scene and craft breweries.', roofingConsiderations: ['Mountain weather extremes', 'Snow and ice loads', 'Steep terrain access', 'Historic Asheville properties', 'Premium mountain home standards'], popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Standing Seam Metal', 'Slate', 'Cedar Shakes'], avgRoofCost: { low: 8000, mid: 15000, high: 35000 }, climate: 'Humid subtropical highland', landmarks: ['Biltmore Estate', 'Blue Ridge Parkway', 'Downtown Asheville'], nearbyCounties: ['henderson-county-nc', 'madison-county-nc', 'yancey-county-nc', 'mcdowell-county-nc', 'haywood-county-nc'], region: 'Mountains' },
  { slug: 'henderson-county-nc', name: 'Henderson County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Hendersonville', population: '120,000+', cities: [], zipCodes: ['28726', '28731', '28732', '28735', '28739', '28742', '28755', '28759', '28790', '28791', '28792'], description: 'Henderson County is apple country with Hendersonville and Flat Rock arts.', roofingConsiderations: ['Mountain climate', 'Apple orchard properties', 'Retirement community standards', 'Historic Flat Rock', 'Seasonal weather extremes'], popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Standing Seam Metal', 'Cedar Shakes'], avgRoofCost: { low: 7000, mid: 13500, high: 28000 }, climate: 'Humid subtropical highland', landmarks: ['Carl Sandburg Home', 'Apple orchards', 'Historic Hendersonville'], nearbyCounties: ['buncombe-county-nc', 'transylvania-county-nc', 'polk-county-nc', 'rutherford-county-nc'], region: 'Mountains' },
  { slug: 'transylvania-county-nc', name: 'Transylvania County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Brevard', population: '35,000+', cities: [], zipCodes: ['28712', '28768', '28772', '28774'], description: 'Transylvania County is Land of Waterfalls with Brevard music scene.', roofingConsiderations: ['High rainfall', 'Waterfall proximity humidity', 'Mountain terrain access', 'Vacation homes', 'Forest debris'], popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Standing Seam Metal'], avgRoofCost: { low: 7000, mid: 13500, high: 28000 }, climate: 'Humid subtropical highland', landmarks: ['Pisgah National Forest', 'Looking Glass Falls', 'Brevard Music Center'], nearbyCounties: ['henderson-county-nc', 'haywood-county-nc', 'jackson-county-nc'], region: 'Mountains' },
  { slug: 'polk-county-nc', name: 'Polk County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Columbus', population: '20,000+', cities: [], zipCodes: ['28722', '28746', '28749', '28756', '28773', '28782'], description: 'Polk County is thermal belt with mild winters and Tryon equestrian culture.', roofingConsiderations: ['Thermal belt weather', 'Equestrian property standards', 'Historic Tryon', 'Vacation homes', 'Mountain exposure'], popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Standing Seam Metal', 'Cedar Shakes'], avgRoofCost: { low: 6500, mid: 12500, high: 26000 }, climate: 'Humid subtropical thermal belt', landmarks: ['FENCE', 'Tryon International Equestrian Center', 'Pearson\'s Falls'], nearbyCounties: ['henderson-county-nc', 'rutherford-county-nc'], region: 'Mountains' },
  { slug: 'rutherford-county-nc', name: 'Rutherford County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Rutherfordton', population: '66,000+', cities: [], zipCodes: ['28018', '28019', '28020', '28040', '28043', '28074', '28114', '28139', '28160', '28167'], description: 'Rutherford County is foothills with Lake Lure and Chimney Rock.', roofingConsiderations: ['Lake properties', 'Mountain terrain', 'Tourism area standards', 'Older foothill homes', 'Storm exposure'], popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Standing Seam Metal'], avgRoofCost: { low: 6000, mid: 11500, high: 24000 }, climate: 'Humid subtropical', landmarks: ['Lake Lure', 'Chimney Rock', 'Isothermal Community College'], nearbyCounties: ['henderson-county-nc', 'polk-county-nc', 'cleveland-county-nc', 'mcdowell-county-nc', 'burke-county-nc'], region: 'Mountains' },
  { slug: 'cleveland-county-nc', name: 'Cleveland County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Shelby', population: '99,000+', cities: [], zipCodes: ['28017', '28020', '28042', '28043', '28073', '28086', '28089', '28090', '28114', '28150', '28152'], description: 'Cleveland County is foothills county with Shelby and Kings Mountain history.', roofingConsiderations: ['Foothills weather', 'Historic properties', 'Mix of old and new', 'Rural access', 'Textile heritage homes'], popularMaterials: ['Architectural Shingles', 'Metal Roofing', '3-Tab Shingles'], avgRoofCost: { low: 5500, mid: 11000, high: 22000 }, climate: 'Humid subtropical', landmarks: ['Kings Mountain National Military Park', 'Earl Scruggs Center', 'Historic Shelby'], nearbyCounties: ['gaston-county-nc', 'rutherford-county-nc', 'lincoln-county-nc', 'burke-county-nc'], region: 'Mountains' },
  { slug: 'burke-county-nc', name: 'Burke County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Morganton', population: '90,000+', cities: [], zipCodes: ['28612', '28630', '28637', '28655', '28666', '28680'], description: 'Burke County is foothills with Morganton and Table Rock outdoor recreation.', roofingConsiderations: ['Mountain weather', 'Outdoor recreation properties', 'Mix of elevations', 'Historic Morganton', 'Rural mountain access'], popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Standing Seam Metal'], avgRoofCost: { low: 5500, mid: 11000, high: 22000 }, climate: 'Humid subtropical with mountain influence', landmarks: ['Table Rock', 'Linville Gorge', 'Historic Morganton'], nearbyCounties: ['caldwell-county-nc', 'catawba-county-nc', 'cleveland-county-nc', 'mcdowell-county-nc', 'avery-county-nc'], region: 'Mountains' },
  { slug: 'caldwell-county-nc', name: 'Caldwell County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Lenoir', population: '82,000+', cities: [], zipCodes: ['28601', '28611', '28618', '28624', '28630', '28638', '28645', '28657'], description: 'Caldwell County is Blue Ridge foothills with furniture heritage and outdoor recreation.', roofingConsiderations: ['Mountain weather', 'Furniture industry buildings', 'Rural access', 'Older homes', 'Mix of elevations'], popularMaterials: ['Metal Roofing', 'Architectural Shingles', '3-Tab Shingles'], avgRoofCost: { low: 5500, mid: 10500, high: 21000 }, climate: 'Humid subtropical with mountain influence', landmarks: ['Grandfather Mountain', 'Wilson Creek', 'Lenoir'], nearbyCounties: ['watauga-county-nc', 'burke-county-nc', 'alexander-county-nc', 'wilkes-county-nc', 'avery-county-nc'], region: 'Mountains' },
  { slug: 'alexander-county-nc', name: 'Alexander County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Taylorsville', population: '38,000+', cities: ['taylorsville-nc'], zipCodes: ['28635', '28636', '28681', '28683', '28689'], description: 'Alexander County is rural foothills between Statesville and the mountains.', roofingConsiderations: ['Rural access', 'Agricultural buildings', 'Older housing', 'Mountain influence', 'Limited contractors'], popularMaterials: ['Metal Roofing', 'Architectural Shingles', '3-Tab Shingles'], avgRoofCost: { low: 5000, mid: 10000, high: 19000 }, climate: 'Humid subtropical', landmarks: ['Lake Hickory', 'Hiddenite gems', 'Taylorsville'], nearbyCounties: ['iredell-county-nc', 'caldwell-county-nc', 'catawba-county-nc', 'wilkes-county-nc'], region: 'Mountains' },
  { slug: 'catawba-county-nc', name: 'Catawba County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Newton', population: '160,000+', cities: ['hickory-nc'], zipCodes: ['28601', '28602', '28609', '28610', '28613', '28630', '28650', '28658', '28678'], description: 'Catawba County features Hickory furniture heritage and Lake Hickory recreation.', roofingConsiderations: ['Lake properties', 'Furniture industry buildings', 'Mix of housing ages', 'Growing suburbs', 'I-40 corridor development'], popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Standing Seam Metal'], avgRoofCost: { low: 6000, mid: 11500, high: 23000 }, climate: 'Humid subtropical', landmarks: ['Lake Hickory', 'Hickory Furniture Mart', 'Catawba Science Center'], nearbyCounties: ['alexander-county-nc', 'burke-county-nc', 'caldwell-county-nc', 'iredell-county-nc', 'lincoln-county-nc'], region: 'Mountains' },
  { slug: 'watauga-county-nc', name: 'Watauga County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Boone', population: '57,000+', cities: [], zipCodes: ['28604', '28605', '28607', '28618', '28626', '28644', '28679', '28684', '28691', '28692', '28698'], description: 'Watauga County is High Country with Boone, App State, and ski resorts.', roofingConsiderations: ['Heavy snow loads', 'Extreme cold', 'Steep mountain terrain', 'University properties', 'Vacation home standards'], popularMaterials: ['Metal Roofing', 'Standing Seam Metal', 'Architectural Shingles', 'Slate'], avgRoofCost: { low: 8000, mid: 15000, high: 32000 }, climate: 'Humid continental highland', landmarks: ['Appalachian State University', 'Blowing Rock', 'Grandfather Mountain'], nearbyCounties: ['ashe-county-nc', 'avery-county-nc', 'caldwell-county-nc', 'wilkes-county-nc'], region: 'Mountains' },
  { slug: 'ashe-county-nc', name: 'Ashe County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Jefferson', population: '27,000+', cities: [], zipCodes: ['28615', '28617', '28627', '28629', '28640', '28643', '28644', '28672', '28693', '28694'], description: 'Ashe County is New River country with Christmas tree farms and cheese tradition.', roofingConsiderations: ['Heavy snow loads', 'Mountain terrain', 'Christmas tree farm buildings', 'Vacation homes', 'Remote access'], popularMaterials: ['Metal Roofing', 'Standing Seam Metal', 'Architectural Shingles'], avgRoofCost: { low: 7000, mid: 13000, high: 26000 }, climate: 'Humid continental highland', landmarks: ['New River', 'Mount Jefferson', 'Ashe County Cheese'], nearbyCounties: ['watauga-county-nc', 'alleghany-county-nc', 'wilkes-county-nc'], region: 'Mountains' },
  { slug: 'alleghany-county-nc', name: 'Alleghany County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Sparta', population: '11,000+', cities: [], zipCodes: ['28623', '28627', '28663', '28672'], description: 'Alleghany County is scenic mountain county on Blue Ridge Parkway.', roofingConsiderations: ['Mountain weather extremes', 'Remote access', 'Vacation properties', 'Snow loads', 'Limited contractors'], popularMaterials: ['Metal Roofing', 'Standing Seam Metal', 'Architectural Shingles'], avgRoofCost: { low: 6500, mid: 12500, high: 25000 }, climate: 'Humid continental highland', landmarks: ['Blue Ridge Parkway', 'New River', 'Sparta'], nearbyCounties: ['ashe-county-nc', 'surry-county-nc', 'wilkes-county-nc'], region: 'Mountains' },
  { slug: 'wilkes-county-nc', name: 'Wilkes County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Wilkesboro', population: '68,000+', cities: [], zipCodes: ['28621', '28624', '28635', '28649', '28651', '28654', '28659', '28665', '28676', '28685', '28697'], description: 'Wilkes County is MerleFest country with moonshine heritage and Blue Ridge foothills.', roofingConsiderations: ['Mountain weather', 'Rural access', 'Mix of elevations', 'Older homes', 'Festival venue properties'], popularMaterials: ['Metal Roofing', 'Architectural Shingles', '3-Tab Shingles', 'Standing Seam Metal'], avgRoofCost: { low: 5500, mid: 11000, high: 22000 }, climate: 'Humid subtropical with mountain influence', landmarks: ['MerleFest', 'Stone Mountain State Park', 'W. Kerr Scott Dam'], nearbyCounties: ['ashe-county-nc', 'alleghany-county-nc', 'watauga-county-nc', 'caldwell-county-nc', 'yadkin-county-nc', 'surry-county-nc'], region: 'Mountains' },
  { slug: 'avery-county-nc', name: 'Avery County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Newland', population: '18,000+', cities: [], zipCodes: ['28604', '28616', '28622', '28646', '28657', '28662'], description: 'Avery County is highest county east of Mississippi with Banner Elk ski resorts.', roofingConsiderations: ['Extreme snow loads', 'High elevation exposure', 'Ski resort properties', 'Vacation homes', 'Mountain terrain challenges'], popularMaterials: ['Metal Roofing', 'Standing Seam Metal', 'Impact-Resistant Shingles'], avgRoofCost: { low: 8000, mid: 15500, high: 34000 }, climate: 'Humid continental highland', landmarks: ['Banner Elk', 'Grandfather Mountain', 'Beech Mountain'], nearbyCounties: ['watauga-county-nc', 'mitchell-county-nc', 'burke-county-nc', 'caldwell-county-nc'], region: 'Mountains' },
  { slug: 'mitchell-county-nc', name: 'Mitchell County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Bakersville', population: '15,000+', cities: [], zipCodes: ['28604', '28705', '28714', '28752', '28765'], description: 'Mitchell County has Roan Mountain rhododendrons and gem mining.', roofingConsiderations: ['High elevation', 'Snow loads', 'Remote mountain access', 'Older homes', 'Limited contractors'], popularMaterials: ['Metal Roofing', 'Standing Seam Metal', 'Architectural Shingles'], avgRoofCost: { low: 6500, mid: 12500, high: 25000 }, climate: 'Humid continental highland', landmarks: ['Roan Mountain', 'Penland School of Craft', 'Gem mining'], nearbyCounties: ['avery-county-nc', 'yancey-county-nc', 'mcdowell-county-nc'], region: 'Mountains' },
  { slug: 'yancey-county-nc', name: 'Yancey County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Burnsville', population: '18,000+', cities: [], zipCodes: ['28701', '28705', '28714', '28740', '28746', '28755', '28785'], description: 'Yancey County has Mount Mitchell, highest peak east of Mississippi.', roofingConsiderations: ['Extreme elevations', 'Heavy snow', 'Mountain terrain', 'Vacation properties', 'Remote access'], popularMaterials: ['Metal Roofing', 'Standing Seam Metal', 'Architectural Shingles'], avgRoofCost: { low: 7000, mid: 13500, high: 28000 }, climate: 'Humid continental highland', landmarks: ['Mount Mitchell', 'Burnsville Town Square', 'Cane River'], nearbyCounties: ['buncombe-county-nc', 'mitchell-county-nc', 'madison-county-nc', 'mcdowell-county-nc'], region: 'Mountains' },
  { slug: 'madison-county-nc', name: 'Madison County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Marshall', population: '22,000+', cities: [], zipCodes: ['28748', '28753', '28754', '28757', '28778', '28787', '28801'], description: 'Madison County is remote mountain county with Hot Springs and French Broad River.', roofingConsiderations: ['Remote mountain access', 'River area flooding', 'Vacation cabins', 'Older farmsteads', 'Limited contractors'], popularMaterials: ['Metal Roofing', 'Standing Seam Metal', 'Architectural Shingles'], avgRoofCost: { low: 6500, mid: 12500, high: 26000 }, climate: 'Humid continental highland', landmarks: ['Hot Springs', 'French Broad River', 'Appalachian Trail'], nearbyCounties: ['buncombe-county-nc', 'yancey-county-nc', 'haywood-county-nc'], region: 'Mountains' },
  { slug: 'haywood-county-nc', name: 'Haywood County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Waynesville', population: '62,000+', cities: [], zipCodes: ['28716', '28721', '28738', '28745', '28751', '28783', '28785', '28786'], description: 'Haywood County has Waynesville charm and Maggie Valley attractions.', roofingConsiderations: ['Mountain weather', 'Tourism properties', 'Ski area proximity', 'Vacation homes', 'Historic Waynesville'], popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Standing Seam Metal', 'Cedar Shakes'], avgRoofCost: { low: 7000, mid: 13000, high: 27000 }, climate: 'Humid subtropical highland', landmarks: ['Maggie Valley', 'Cataloochee Ski Area', 'Downtown Waynesville'], nearbyCounties: ['buncombe-county-nc', 'madison-county-nc', 'jackson-county-nc', 'transylvania-county-nc', 'swain-county-nc'], region: 'Mountains' },
  { slug: 'mcdowell-county-nc', name: 'McDowell County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Marion', population: '45,000+', cities: [], zipCodes: ['28711', '28752', '28756', '28761', '28762'], description: 'McDowell County has Marion and Lake James recreation.', roofingConsiderations: ['Lake properties', 'Mountain weather', 'Mix of housing ages', 'Industrial buildings', 'Growing recreation area'], popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Standing Seam Metal'], avgRoofCost: { low: 6000, mid: 11500, high: 23000 }, climate: 'Humid subtropical with mountain influence', landmarks: ['Lake James', 'Linville Caverns', 'Marion downtown'], nearbyCounties: ['burke-county-nc', 'buncombe-county-nc', 'rutherford-county-nc', 'yancey-county-nc', 'mitchell-county-nc'], region: 'Mountains' },
  { slug: 'jackson-county-nc', name: 'Jackson County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Sylva', population: '45,000+', cities: [], zipCodes: ['28717', '28719', '28723', '28725', '28734', '28736', '28779', '28783', '28788', '28789'], description: 'Jackson County has WCU, Cherokee casino, and Great Smoky Mountains gateway.', roofingConsiderations: ['Mountain terrain', 'University properties', 'Casino area development', 'Vacation homes', 'High rainfall'], popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Standing Seam Metal'], avgRoofCost: { low: 7000, mid: 13000, high: 27000 }, climate: 'Humid subtropical highland', landmarks: ['Western Carolina University', 'Harrah\'s Cherokee', 'Great Smoky Mountains'], nearbyCounties: ['haywood-county-nc', 'swain-county-nc', 'macon-county-nc', 'transylvania-county-nc'], region: 'Mountains' },
  { slug: 'swain-county-nc', name: 'Swain County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Bryson City', population: '15,000+', cities: [], zipCodes: ['28713', '28719', '28733', '28771', '28789'], description: 'Swain County is Great Smoky Mountains gateway with Nantahala rafting.', roofingConsiderations: ['Remote mountain access', 'National Park proximity', 'Vacation rentals', 'Heavy rainfall', 'Limited contractors'], popularMaterials: ['Metal Roofing', 'Standing Seam Metal', 'Architectural Shingles'], avgRoofCost: { low: 7000, mid: 13500, high: 28000 }, climate: 'Humid subtropical highland', landmarks: ['Great Smoky Mountains', 'Nantahala River', 'Bryson City train'], nearbyCounties: ['jackson-county-nc', 'haywood-county-nc', 'graham-county-nc', 'macon-county-nc'], region: 'Mountains' },
  { slug: 'graham-county-nc', name: 'Graham County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Robbinsville', population: '8,500+', cities: [], zipCodes: ['28771', '28772'], description: 'Graham County is remote mountain county with Joyce Kilmer Forest and lake recreation.', roofingConsiderations: ['Remote access', 'Lake properties', 'Mountain extremes', 'Limited contractors', 'Vacation cabins'], popularMaterials: ['Metal Roofing', 'Standing Seam Metal'], avgRoofCost: { low: 6500, mid: 12500, high: 25000 }, climate: 'Humid subtropical highland', landmarks: ['Joyce Kilmer Memorial Forest', 'Lake Santeetlah', 'Tail of the Dragon'], nearbyCounties: ['swain-county-nc', 'cherokee-county-nc', 'macon-county-nc'], region: 'Mountains' },
  { slug: 'cherokee-county-nc', name: 'Cherokee County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Murphy', population: '29,000+', cities: [], zipCodes: ['28901', '28902', '28903', '28904', '28905', '28906'], description: 'Cherokee County is far western NC with Murphy as gateway to Smoky Mountains.', roofingConsiderations: ['Remote mountain location', 'Lake properties', 'Vacation homes', 'Limited contractors', 'Mountain weather'], popularMaterials: ['Metal Roofing', 'Standing Seam Metal', 'Architectural Shingles'], avgRoofCost: { low: 6000, mid: 12000, high: 24000 }, climate: 'Humid subtropical highland', landmarks: ['Lake Hiwassee', 'Fields of the Wood', 'Murphy downtown'], nearbyCounties: ['graham-county-nc', 'clay-county-nc', 'macon-county-nc'], region: 'Mountains' },
  { slug: 'clay-county-nc', name: 'Clay County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Hayesville', population: '11,500+', cities: [], zipCodes: ['28904'], description: 'Clay County is small mountain county with Lake Chatuge and peaceful retirement living.', roofingConsiderations: ['Lake properties', 'Retirement community standards', 'Mountain weather', 'Remote access', 'Limited contractors'], popularMaterials: ['Metal Roofing', 'Standing Seam Metal', 'Architectural Shingles'], avgRoofCost: { low: 6000, mid: 11500, high: 23000 }, climate: 'Humid subtropical highland', landmarks: ['Lake Chatuge', 'John C. Campbell Folk School', 'Hayesville'], nearbyCounties: ['cherokee-county-nc', 'macon-county-nc'], region: 'Mountains' },
  { slug: 'macon-county-nc', name: 'Macon County', state: 'North Carolina', stateAbbr: 'NC', countySeat: 'Franklin', population: '37,000+', cities: [], zipCodes: ['28734', '28741', '28744', '28763', '28775'], description: 'Macon County has Franklin gem capital and Nantahala National Forest.', roofingConsiderations: ['Mountain terrain', 'Gem mining properties', 'Vacation homes', 'Forest proximity', 'High rainfall'], popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Standing Seam Metal'], avgRoofCost: { low: 6500, mid: 12500, high: 25000 }, climate: 'Humid subtropical highland', landmarks: ['Franklin gem mines', 'Nantahala National Forest', 'Cullasaja Falls'], nearbyCounties: ['jackson-county-nc', 'swain-county-nc', 'clay-county-nc', 'cherokee-county-nc', 'graham-county-nc'], region: 'Mountains' },
];

// Utility functions
export function getCountyBySlug(slug: string): CountyData | undefined {
  return ncCounties.find(county => county.slug === slug);
}

export function getAllCountySlugs(): string[] {
  return ncCounties.map(county => county.slug);
}

export function getCountiesByRegion(region: string): CountyData[] {
  return ncCounties.filter(county => county.region === region);
}

export function getCountyByCitySlug(citySlug: string): CountyData | undefined {
  return ncCounties.find(county => county.cities.includes(citySlug));
}

export function getNearbyCounties(countySlug: string): CountyData[] {
  const county = getCountyBySlug(countySlug);
  if (!county) return [];
  return county.nearbyCounties
    .map(slug => getCountyBySlug(slug))
    .filter((c): c is CountyData => c !== undefined);
}
