import { locations, LocationData } from './locations';

export interface StateData {
  slug: string;
  name: string;
  abbr: string;
  description: string;
  climate: string;
  roofingConsiderations: string[];
  popularMaterials: string[];
  averageCostRange: { low: number; high: number };
  majorMetros: string[];
  licensingInfo: string;
  insuranceNotes: string;
}

export const stateData: Record<string, StateData> = {
  'texas': {
    slug: 'texas',
    name: 'Texas',
    abbr: 'TX',
    description: 'Texas is the second-largest state in the US, with diverse climate zones ranging from humid subtropical in the east to semi-arid in the west. The state experiences significant roofing challenges including severe hail storms, hurricanes along the Gulf Coast, and intense summer heat.',
    climate: 'Varies from humid subtropical to semi-arid desert',
    roofingConsiderations: [
      'Severe hail damage is common, especially in North Texas (Hail Alley)',
      'Hurricane and tropical storm damage along the Gulf Coast',
      'Extreme summer heat accelerates roof aging',
      'Impact-resistant shingles often qualify for insurance discounts',
      'Proper attic ventilation is critical due to heat',
    ],
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Clay Tiles', 'Architectural Shingles', 'TPO for flat roofs'],
    averageCostRange: { low: 7500, high: 23000 },
    majorMetros: ['Houston', 'Dallas', 'San Antonio', 'Austin', 'Fort Worth'],
    licensingInfo: 'Texas does not require a state roofing license, but many cities require permits and some require local contractor registration.',
    insuranceNotes: 'Many Texas insurers offer discounts for Class 4 impact-resistant shingles. Hail and wind damage claims are common.',
  },
  'florida': {
    slug: 'florida',
    name: 'Florida',
    abbr: 'FL',
    description: 'Florida presents unique roofing challenges due to its tropical and subtropical climate, frequent hurricanes, and strict building codes. The state has some of the most stringent roofing requirements in the nation to protect against high winds and storm damage.',
    climate: 'Tropical and humid subtropical',
    roofingConsiderations: [
      'Florida Building Code requires hurricane-resistant roofing in most areas',
      'Wind ratings up to 150+ mph may be required in coastal zones',
      'Salt air corrosion is a concern in coastal areas',
      'High humidity promotes algae and mold growth',
      'Annual inspections are often required for insurance',
    ],
    popularMaterials: ['Metal Roofing', 'Concrete Tiles', 'Hurricane-Rated Shingles', 'TPO for flat roofs', 'Standing Seam Metal'],
    averageCostRange: { low: 8000, high: 28000 },
    majorMetros: ['Miami', 'Tampa', 'Orlando', 'Jacksonville'],
    licensingInfo: 'Florida requires a state roofing contractor license. Contractors must pass exams and carry insurance.',
    insuranceNotes: 'Many Florida insurers require roof inspections before issuing policies. Roofs over 15-20 years may need replacement for coverage.',
  },
  'california': {
    slug: 'california',
    name: 'California',
    abbr: 'CA',
    description: 'California offers diverse roofing conditions from Mediterranean climates in the south to cooler, wetter conditions in the north. Title 24 energy efficiency requirements and fire-resistant material mandates in many areas make roofing particularly specialized.',
    climate: 'Mediterranean to oceanic, varies by region',
    roofingConsiderations: [
      'Title 24 energy efficiency requirements affect material choices',
      'Fire-resistant Class A roofing required in many WUI zones',
      'Cool roof requirements in many jurisdictions',
      'Seismic considerations for heavy tile roofs',
      'Drought conditions can stress wood roofing',
    ],
    popularMaterials: ['Spanish Tiles', 'Metal Roofing', 'Cool Roofing', 'Flat Roofing Systems', 'Concrete Tiles'],
    averageCostRange: { low: 11000, high: 35000 },
    majorMetros: ['Los Angeles', 'San Diego', 'San Francisco', 'San Jose'],
    licensingInfo: 'California requires a C-39 Roofing Contractor license through the Contractors State License Board (CSLB).',
    insuranceNotes: 'Fire insurance is increasingly difficult to obtain in high-risk areas. Fire-resistant roofing materials may be required.',
  },
  'north-carolina': {
    slug: 'north-carolina',
    name: 'North Carolina',
    abbr: 'NC',
    description: 'North Carolina offers a moderate humid subtropical climate ideal for most roofing materials. The state experiences all four seasons, occasional hurricanes in coastal areas, and has a rapidly growing population creating high demand for roofing services.',
    climate: 'Humid subtropical with four distinct seasons',
    roofingConsiderations: [
      'Hurricane and tropical storm damage possible, especially in coastal regions',
      'Humid conditions can promote algae growth on shingles',
      'Occasional ice and snow in western mountains and Piedmont',
      'Strong thunderstorms are common in spring and summer',
      'Tree debris from storms is a common cause of damage',
    ],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate', 'Cedar Shakes', 'Designer Shingles'],
    averageCostRange: { low: 6800, high: 24000 },
    majorMetros: ['Charlotte', 'Raleigh', 'Lake Norman', 'Concord', 'Gastonia'],
    licensingInfo: 'North Carolina requires roofing contractors to be licensed through the NC Licensing Board for General Contractors for projects over $30,000.',
    insuranceNotes: 'Coastal counties may have higher insurance requirements. Wind and hail deductibles are common.',
  },
  'georgia': {
    slug: 'georgia',
    name: 'Georgia',
    abbr: 'GA',
    description: 'Georgia features a humid subtropical climate with hot summers and mild winters. The state is known for severe thunderstorms, occasional tornadoes, and high humidity that affects roofing longevity.',
    climate: 'Humid subtropical',
    roofingConsiderations: [
      'Severe thunderstorms and occasional tornadoes',
      'High humidity promotes mold and algae growth',
      'Heavy rainfall requires proper drainage',
      'Hot summers accelerate shingle aging',
      'Tree debris from storms is common',
    ],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate', 'Asphalt Shingles'],
    averageCostRange: { low: 7000, high: 21000 },
    majorMetros: ['Atlanta', 'Savannah', 'Augusta', 'Columbus'],
    licensingInfo: 'Georgia requires residential and general contractors to be licensed. Requirements vary by county.',
    insuranceNotes: 'Standard homeowner policies cover most storm damage. Hail damage claims are common in North Georgia.',
  },
  'arizona': {
    slug: 'arizona',
    name: 'Arizona',
    abbr: 'AZ',
    description: 'Arizona presents extreme desert conditions with intense heat, UV exposure, and monsoon storms. The state requires roofing materials specifically designed to handle temperature extremes and occasional flash flooding.',
    climate: 'Hot desert to semi-arid',
    roofingConsiderations: [
      'Extreme heat (110°F+) requires heat-resistant materials',
      'Intense UV exposure accelerates material degradation',
      'Monsoon storms bring flash flooding and wind damage',
      'Thermal shock from rapid temperature changes',
      'Cool roofing is highly beneficial for energy savings',
    ],
    popularMaterials: ['Clay Tiles', 'Concrete Tiles', 'Metal Roofing', 'TPO Flat Roofing', 'Cool Roofing'],
    averageCostRange: { low: 8000, high: 20000 },
    majorMetros: ['Phoenix', 'Tucson', 'Mesa', 'Scottsdale'],
    licensingInfo: 'Arizona requires roofing contractors to hold a CR-42 Roofing license from the Arizona Registrar of Contractors.',
    insuranceNotes: 'Monsoon damage is typically covered. UV damage is considered normal wear and not typically covered.',
  },
  'colorado': {
    slug: 'colorado',
    name: 'Colorado',
    abbr: 'CO',
    description: 'Colorado is notorious for severe hail storms, heavy snow, and intense UV exposure at altitude. The state consistently ranks among the highest for hail damage claims in the nation.',
    climate: 'Semi-arid continental with heavy snow',
    roofingConsiderations: [
      'Severe hail damage is extremely common',
      'Heavy snow loads require sturdy roofing systems',
      'Ice dam formation in winter',
      'Intense UV at high altitude accelerates aging',
      'Rapid temperature swings cause thermal stress',
    ],
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Slate', 'Architectural Shingles'],
    averageCostRange: { low: 9000, high: 24000 },
    majorMetros: ['Denver', 'Colorado Springs', 'Aurora', 'Boulder'],
    licensingInfo: 'Colorado does not require a state roofing license, but many municipalities require local licensing.',
    insuranceNotes: 'Impact-resistant (Class 4) shingles often qualify for significant insurance discounts. Hail claims are extremely common.',
  },
  'tennessee': {
    slug: 'tennessee',
    name: 'Tennessee',
    abbr: 'TN',
    description: 'Tennessee has a humid subtropical climate with all four seasons. The state experiences severe thunderstorms, tornadoes, and rapid growth in major cities creating high demand for roofing services.',
    climate: 'Humid subtropical',
    roofingConsiderations: [
      'Severe thunderstorms and tornado risk',
      'High humidity promotes algae growth',
      'Temperature fluctuations between seasons',
      'Heavy rainfall requires good drainage',
      'Rapid development increases contractor demand',
    ],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Cedar Shakes', 'Asphalt Shingles'],
    averageCostRange: { low: 7000, high: 20000 },
    majorMetros: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga'],
    licensingInfo: 'Tennessee requires contractors to be licensed through the State Board for Licensing Contractors for projects over $25,000.',
    insuranceNotes: 'Storm damage coverage is standard. Tornado damage claims occur regularly in West and Middle Tennessee.',
  },
  'south-carolina': {
    slug: 'south-carolina',
    name: 'South Carolina',
    abbr: 'SC',
    description: 'South Carolina features a humid subtropical climate with hot summers and mild winters. Coastal areas face hurricane threats, while the entire state experiences strong thunderstorms and high humidity.',
    climate: 'Humid subtropical',
    roofingConsiderations: [
      'Hurricane and tropical storm damage in coastal areas',
      'High humidity promotes mold and algae growth',
      'Strong thunderstorms and occasional hail',
      'Salt air corrosion near the coast',
      'Hot summers accelerate shingle aging',
    ],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Hurricane-Rated Shingles', 'Slate'],
    averageCostRange: { low: 6800, high: 23000 },
    majorMetros: ['Charleston', 'Columbia', 'Greenville', 'Rock Hill', 'Fort Mill'],
    licensingInfo: 'South Carolina requires residential contractor licensing through SC LLR for projects over $5,000.',
    insuranceNotes: 'Coastal areas have higher wind deductibles. Hurricane damage claims are common in the Lowcountry.',
  },
  'new-york': {
    slug: 'new-york',
    name: 'New York',
    abbr: 'NY',
    description: 'New York features diverse roofing challenges from harsh winters upstate to unique urban conditions in New York City. The state requires specialized approaches for historic buildings, flat roofs, and snow load management.',
    climate: 'Humid continental with cold winters',
    roofingConsiderations: [
      'Heavy snow loads in upstate regions',
      'Ice dam formation is common',
      'Many flat roofs in urban areas require specialized systems',
      'Historic preservation requirements in some districts',
      'High labor costs in NYC metro area',
    ],
    popularMaterials: ['Architectural Shingles', 'EPDM Flat Roofing', 'Metal Roofing', 'Slate', 'TPO'],
    averageCostRange: { low: 9000, high: 35000 },
    majorMetros: ['New York City', 'Buffalo', 'Rochester', 'Albany'],
    licensingInfo: 'New York City requires contractor licensing. Upstate requirements vary by municipality.',
    insuranceNotes: 'Wind and hail coverage standard. Flood insurance may be required in some areas.',
  },
  'massachusetts': {
    slug: 'massachusetts',
    name: 'Massachusetts',
    abbr: 'MA',
    description: 'Massachusetts experiences harsh New England winters with heavy snow, ice storms, and nor\'easters. The state has many historic homes requiring specialized roofing approaches and materials.',
    climate: 'Humid continental with harsh winters',
    roofingConsiderations: [
      'Heavy snow loads and ice dams are major concerns',
      'Nor\'easters bring significant wind and precipitation',
      'Historic home preservation requirements',
      'Coastal areas face salt air corrosion',
      'Short roofing season due to weather',
    ],
    popularMaterials: ['Architectural Shingles', 'Slate', 'Metal Roofing', 'Cedar Shakes', 'EPDM'],
    averageCostRange: { low: 10000, high: 30000 },
    majorMetros: ['Boston', 'Worcester', 'Springfield', 'Cambridge'],
    licensingInfo: 'Massachusetts requires roofing contractors to be registered with the state and carry insurance.',
    insuranceNotes: 'Wind damage from nor\'easters is commonly covered. Ice dam damage may require separate endorsements.',
  },
  'washington': {
    slug: 'washington',
    name: 'Washington',
    abbr: 'WA',
    description: 'Washington state has dramatic climate differences between the wet western region and the drier eastern interior. The Pacific Northwest\'s famous rain requires exceptional waterproofing and moss prevention.',
    climate: 'Oceanic in west, semi-arid in east',
    roofingConsiderations: [
      'Frequent rain requires excellent water resistance',
      'Moss and algae growth is common in western WA',
      'Snow loads in mountain and eastern regions',
      'Cool, damp conditions affect material longevity',
      'Green building practices are popular',
    ],
    popularMaterials: ['Metal Roofing', 'Composition Shingles', 'Cedar Shakes', 'TPO', 'Architectural Shingles'],
    averageCostRange: { low: 8500, high: 27000 },
    majorMetros: ['Seattle', 'Tacoma', 'Spokane', 'Vancouver'],
    licensingInfo: 'Washington requires roofing contractors to be registered and bonded through L&I.',
    insuranceNotes: 'Water damage coverage is essential. Moss damage is typically not covered as it\'s preventable maintenance.',
  },
  'ohio': {
    slug: 'ohio',
    name: 'Ohio',
    abbr: 'OH',
    description: 'Ohio experiences all four seasons with cold, snowy winters and hot, humid summers. Lake effect snow in northern regions and severe thunderstorms statewide create diverse roofing challenges.',
    climate: 'Humid continental',
    roofingConsiderations: [
      'Lake effect snow in northern Ohio',
      'Ice dam formation in winter',
      'Severe thunderstorms and occasional hail',
      'Humid summers promote algae growth',
      'Freeze-thaw cycles stress roofing materials',
    ],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles', 'EPDM', 'Slate'],
    averageCostRange: { low: 7000, high: 20000 },
    majorMetros: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo'],
    licensingInfo: 'Ohio does not require a state roofing license, but many municipalities have local requirements.',
    insuranceNotes: 'Wind and hail damage are commonly covered. Lake effect snow damage claims occur in northern Ohio.',
  },
  'michigan': {
    slug: 'michigan',
    name: 'Michigan',
    abbr: 'MI',
    description: 'Michigan\'s Great Lakes location creates unique roofing challenges including heavy lake effect snow, high humidity, and harsh winters. The state requires roofing systems designed for significant snow loads.',
    climate: 'Humid continental with lake effect',
    roofingConsiderations: [
      'Heavy lake effect snow requires sturdy roofing',
      'Ice dam prevention is critical',
      'High humidity promotes algae and moss',
      'Freeze-thaw cycles cause material stress',
      'Short optimal roofing season',
    ],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles', 'EPDM'],
    averageCostRange: { low: 7500, high: 20000 },
    majorMetros: ['Detroit', 'Grand Rapids', 'Ann Arbor', 'Lansing'],
    licensingInfo: 'Michigan requires residential builders to be licensed. Roofing falls under this category.',
    insuranceNotes: 'Wind and hail coverage standard. Ice dam damage may require additional endorsement.',
  },
  'louisiana': {
    slug: 'louisiana',
    name: 'Louisiana',
    abbr: 'LA',
    description: 'Louisiana faces significant roofing challenges from its tropical climate, frequent hurricanes, and extreme humidity. The state requires wind-resistant roofing in most areas.',
    climate: 'Humid subtropical to tropical',
    roofingConsiderations: [
      'Hurricane and tropical storm damage is common',
      'Extreme humidity promotes mold and algae',
      'Heavy rainfall requires excellent drainage',
      'Wind-resistant materials are essential',
      'Salt air corrosion in coastal areas',
    ],
    popularMaterials: ['Metal Roofing', 'Hurricane-Rated Shingles', 'Slate', 'Architectural Shingles'],
    averageCostRange: { low: 8000, high: 25000 },
    majorMetros: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette'],
    licensingInfo: 'Louisiana requires contractor licensing through the Louisiana State Licensing Board for Contractors.',
    insuranceNotes: 'Hurricane deductibles are common. Many insurers require recent roof inspections for coastal properties.',
  },
  'alabama': {
    slug: 'alabama',
    name: 'Alabama',
    abbr: 'AL',
    description: 'Alabama has a humid subtropical climate with hot summers and risk of tornadoes and severe storms. The state is in Tornado Alley\'s southeastern extension.',
    climate: 'Humid subtropical',
    roofingConsiderations: [
      'Tornado risk is significant, especially in spring',
      'Severe thunderstorms with high winds',
      'High humidity promotes algae growth',
      'Hot summers stress roofing materials',
      'Hurricane impacts possible in southern regions',
    ],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Impact-Resistant Shingles', 'Asphalt Shingles'],
    averageCostRange: { low: 7000, high: 19000 },
    majorMetros: ['Birmingham', 'Montgomery', 'Huntsville', 'Mobile'],
    licensingInfo: 'Alabama requires contractors to be licensed for projects over $50,000. Local requirements vary.',
    insuranceNotes: 'Storm and tornado damage commonly covered. Wind deductibles may apply.',
  },
  'pennsylvania': {
    slug: 'pennsylvania',
    name: 'Pennsylvania',
    abbr: 'PA',
    description: 'Pennsylvania experiences all four seasons with cold, snowy winters and warm, humid summers. The state has diverse roofing needs from urban Philadelphia to rural mountain regions.',
    climate: 'Humid continental',
    roofingConsiderations: [
      'Heavy snow loads in mountain regions',
      'Ice dam formation is common',
      'Historic home preservation in older cities',
      'Freeze-thaw cycles stress materials',
      'Occasional severe thunderstorms',
    ],
    popularMaterials: ['Architectural Shingles', 'Slate', 'Metal Roofing', 'EPDM'],
    averageCostRange: { low: 8000, high: 25000 },
    majorMetros: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Erie'],
    licensingInfo: 'Pennsylvania requires home improvement contractor registration through the Attorney General\'s office.',
    insuranceNotes: 'Wind and hail coverage standard. Snow damage claims common in mountain areas.',
  },
  'illinois': {
    slug: 'illinois',
    name: 'Illinois',
    abbr: 'IL',
    description: 'Illinois features harsh winters with significant snowfall and hot, humid summers. The Chicago area faces lake effect weather while southern Illinois has milder conditions.',
    climate: 'Humid continental',
    roofingConsiderations: [
      'Heavy snow and ice in northern regions',
      'Lake effect weather near Chicago',
      'Severe thunderstorms and occasional tornadoes',
      'Ice dam prevention essential',
      'High winds off Lake Michigan',
    ],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'EPDM Flat Roofing', 'Asphalt Shingles'],
    averageCostRange: { low: 8000, high: 25000 },
    majorMetros: ['Chicago', 'Aurora', 'Rockford', 'Springfield'],
    licensingInfo: 'Illinois requires roofing contractor licensing in Chicago and some municipalities. State registration required.',
    insuranceNotes: 'Wind and hail damage common. Tornado coverage typically included in standard policies.',
  },
  'virginia': {
    slug: 'virginia',
    name: 'Virginia',
    abbr: 'VA',
    description: 'Virginia offers a moderate climate with four seasons. The state ranges from coastal areas prone to hurricanes to mountain regions with snow.',
    climate: 'Humid subtropical to humid continental',
    roofingConsiderations: [
      'Hurricane risk in coastal areas',
      'Snow loads in western mountains',
      'High humidity promotes algae growth',
      'Historic preservation requirements in some areas',
      'Four-season weather allows flexible scheduling',
    ],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate', 'Cedar Shakes'],
    averageCostRange: { low: 7500, high: 22000 },
    majorMetros: ['Virginia Beach', 'Norfolk', 'Richmond', 'Arlington'],
    licensingInfo: 'Virginia requires contractor licensing through the Department of Professional and Occupational Regulation.',
    insuranceNotes: 'Coastal areas may have wind deductibles. Hurricane damage covered by standard policies.',
  },
  'new-jersey': {
    slug: 'new-jersey',
    name: 'New Jersey',
    abbr: 'NJ',
    description: 'New Jersey experiences all four seasons with cold winters and hot summers. The state\'s dense population and coastal exposure create unique roofing challenges.',
    climate: 'Humid subtropical to humid continental',
    roofingConsiderations: [
      'Nor\'easters bring significant wind and precipitation',
      'Coastal areas face salt air corrosion',
      'Dense development means many flat roofs',
      'Snow and ice accumulation in winter',
      'High labor costs in NYC metro area',
    ],
    popularMaterials: ['Architectural Shingles', 'Flat Roofing Systems', 'Metal Roofing', 'Slate'],
    averageCostRange: { low: 9000, high: 27000 },
    majorMetros: ['Newark', 'Jersey City', 'Paterson', 'Trenton'],
    licensingInfo: 'New Jersey requires home improvement contractor registration with the Division of Consumer Affairs.',
    insuranceNotes: 'Flood insurance required in many coastal areas. Wind damage commonly covered.',
  },
  'indiana': {
    slug: 'indiana',
    name: 'Indiana',
    abbr: 'IN',
    description: 'Indiana has a humid continental climate with cold winters and warm summers. The state experiences severe thunderstorms and occasional tornadoes.',
    climate: 'Humid continental',
    roofingConsiderations: [
      'Severe thunderstorms and tornado risk',
      'Heavy snow in northern regions',
      'Ice dam formation in winter',
      'Hail damage is common',
      'Freeze-thaw cycles affect materials',
    ],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles', 'Impact-Resistant Shingles'],
    averageCostRange: { low: 7000, high: 19000 },
    majorMetros: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend'],
    licensingInfo: 'Indiana does not require a state roofing license. Local licensing requirements vary.',
    insuranceNotes: 'Hail and wind damage commonly covered. Tornado damage included in standard policies.',
  },
  'missouri': {
    slug: 'missouri',
    name: 'Missouri',
    abbr: 'MO',
    description: 'Missouri has a humid continental climate with hot summers and cold winters. The state is prone to severe weather including tornadoes, hail, and ice storms.',
    climate: 'Humid continental to humid subtropical',
    roofingConsiderations: [
      'Severe thunderstorms and tornado risk',
      'Significant hail damage potential',
      'Ice storms in winter',
      'Hot, humid summers stress materials',
      'Impact-resistant materials recommended',
    ],
    popularMaterials: ['Impact-Resistant Shingles', 'Architectural Shingles', 'Metal Roofing', 'Slate'],
    averageCostRange: { low: 7000, high: 20000 },
    majorMetros: ['Kansas City', 'St. Louis', 'Springfield', 'Columbia'],
    licensingInfo: 'Missouri does not require a state roofing license. Kansas City and St. Louis have local requirements.',
    insuranceNotes: 'Impact-resistant shingles may qualify for discounts. Hail claims are very common.',
  },
  'maryland': {
    slug: 'maryland',
    name: 'Maryland',
    abbr: 'MD',
    description: 'Maryland has a varied climate from the coastal Eastern Shore to the mountain regions in the west. The state experiences hurricanes, snow, and humid summers.',
    climate: 'Humid subtropical',
    roofingConsiderations: [
      'Hurricane risk on the Eastern Shore and coast',
      'Snow loads in western mountains',
      'High humidity promotes algae growth',
      'Historic preservation in Baltimore and Annapolis',
      'Salt air corrosion near Chesapeake Bay',
    ],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Flat Roofing', 'Slate'],
    averageCostRange: { low: 8000, high: 24000 },
    majorMetros: ['Baltimore', 'Frederick', 'Rockville', 'Gaithersburg'],
    licensingInfo: 'Maryland requires home improvement contractor licensing through MHIC.',
    insuranceNotes: 'Coastal areas have hurricane deductibles. Standard policies cover most storm damage.',
  },
  'wisconsin': {
    slug: 'wisconsin',
    name: 'Wisconsin',
    abbr: 'WI',
    description: 'Wisconsin experiences harsh winters with heavy snowfall and lake effect weather. The state requires roofing systems designed for significant snow and ice loads.',
    climate: 'Humid continental with harsh winters',
    roofingConsiderations: [
      'Heavy snow loads require sturdy roofing',
      'Ice dam prevention is critical',
      'Lake effect snow near Lake Michigan',
      'Short optimal roofing season',
      'Freeze-thaw cycles stress materials',
    ],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'EPDM', 'Asphalt Shingles'],
    averageCostRange: { low: 7500, high: 21000 },
    majorMetros: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha'],
    licensingInfo: 'Wisconsin requires dwelling contractor certification for residential work.',
    insuranceNotes: 'Wind and hail coverage standard. Ice dam damage may need separate coverage.',
  },
  'minnesota': {
    slug: 'minnesota',
    name: 'Minnesota',
    abbr: 'MN',
    description: 'Minnesota has some of the most extreme winter conditions in the lower 48 states. Heavy snow, ice, and severely cold temperatures create demanding roofing requirements.',
    climate: 'Humid continental with severe winters',
    roofingConsiderations: [
      'Extreme cold and heavy snow',
      'Ice dam formation is a major issue',
      'Very short roofing season',
      'Proper attic insulation critical',
      'Metal roofing popular for snow shedding',
    ],
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Ice-Resistant Systems', 'EPDM'],
    averageCostRange: { low: 8000, high: 23000 },
    majorMetros: ['Minneapolis', 'St. Paul', 'Rochester', 'Duluth'],
    licensingInfo: 'Minnesota requires residential contractor licensing through the Department of Labor and Industry.',
    insuranceNotes: 'Ice dam coverage important. Wind and hail damage commonly covered.',
  },
  'connecticut': {
    slug: 'connecticut',
    name: 'Connecticut',
    abbr: 'CT',
    description: 'Connecticut experiences New England winters with significant snow and ice. The state has many historic homes requiring specialized roofing approaches.',
    climate: 'Humid continental',
    roofingConsiderations: [
      'Heavy snow and ice accumulation',
      'Nor\'easters bring wind and precipitation',
      'Historic home preservation requirements',
      'Coastal areas face salt air and hurricanes',
      'Ice dam prevention essential',
    ],
    popularMaterials: ['Architectural Shingles', 'Slate', 'Cedar Shakes', 'Metal Roofing'],
    averageCostRange: { low: 9000, high: 26000 },
    majorMetros: ['Hartford', 'New Haven', 'Stamford', 'Bridgeport'],
    licensingInfo: 'Connecticut requires home improvement contractor registration with the Department of Consumer Protection.',
    insuranceNotes: 'Wind damage from nor\'easters covered. Coastal areas may have wind deductibles.',
  },
  'oklahoma': {
    slug: 'oklahoma',
    name: 'Oklahoma',
    abbr: 'OK',
    description: 'Oklahoma is in the heart of Tornado Alley with severe weather including tornadoes, hail, and high winds. Impact-resistant roofing is highly recommended.',
    climate: 'Humid subtropical with severe storms',
    roofingConsiderations: [
      'Tornado risk is very high',
      'Severe hail damage common',
      'High winds year-round',
      'Impact-resistant materials essential',
      'Hot summers stress materials',
    ],
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Architectural Shingles', 'Stone-Coated Steel'],
    averageCostRange: { low: 7000, high: 19000 },
    majorMetros: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow'],
    licensingInfo: 'Oklahoma does not require a state roofing license. Some municipalities have local requirements.',
    insuranceNotes: 'Impact-resistant shingles qualify for significant discounts. Hail claims very common.',
  },
  'oregon': {
    slug: 'oregon',
    name: 'Oregon',
    abbr: 'OR',
    description: 'Oregon has a wet western region and drier eastern interior. The Pacific Northwest rain requires excellent waterproofing and moss prevention strategies.',
    climate: 'Oceanic in west, semi-arid in east',
    roofingConsiderations: [
      'Heavy rainfall in western Oregon',
      'Moss and algae growth common',
      'Snow loads in mountain areas',
      'Fire risk in eastern Oregon',
      'Green building practices popular',
    ],
    popularMaterials: ['Metal Roofing', 'Composition Shingles', 'Cedar Shakes', 'TPO'],
    averageCostRange: { low: 8500, high: 24000 },
    majorMetros: ['Portland', 'Salem', 'Eugene', 'Bend'],
    licensingInfo: 'Oregon requires contractor licensing through the Construction Contractors Board.',
    insuranceNotes: 'Water damage coverage essential. Fire insurance important in eastern regions.',
  },
  'kentucky': {
    slug: 'kentucky',
    name: 'Kentucky',
    abbr: 'KY',
    description: 'Kentucky has a humid subtropical climate with four distinct seasons. The state experiences severe thunderstorms, occasional tornadoes, and winter ice storms.',
    climate: 'Humid subtropical',
    roofingConsiderations: [
      'Severe thunderstorms and occasional tornadoes',
      'Ice storms in winter',
      'High humidity promotes algae growth',
      'Hot summers stress materials',
      'Hail damage possible',
    ],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles', 'Slate'],
    averageCostRange: { low: 7000, high: 18000 },
    majorMetros: ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro'],
    licensingInfo: 'Kentucky does not require a state roofing license. Local licensing requirements vary.',
    insuranceNotes: 'Storm damage commonly covered. Ice storm claims occur periodically.',
  },
  'nevada': {
    slug: 'nevada',
    name: 'Nevada',
    abbr: 'NV',
    description: 'Nevada has an arid desert climate with extreme heat in the south and snow in mountain areas. UV protection and heat resistance are critical considerations.',
    climate: 'Hot desert to semi-arid',
    roofingConsiderations: [
      'Extreme heat requires UV-resistant materials',
      'Desert sun accelerates material aging',
      'Cool roofing reduces energy costs',
      'Snow loads in mountain areas',
      'Monsoon storms in summer',
    ],
    popularMaterials: ['Tile Roofing', 'Metal Roofing', 'TPO Flat Roofing', 'Cool Roofing'],
    averageCostRange: { low: 8000, high: 22000 },
    majorMetros: ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas'],
    licensingInfo: 'Nevada requires contractor licensing through the State Contractors Board.',
    insuranceNotes: 'UV damage is considered normal wear. Monsoon damage typically covered.',
  },
  'arkansas': {
    slug: 'arkansas',
    name: 'Arkansas',
    abbr: 'AR',
    description: 'Arkansas has a humid subtropical climate with hot summers and risk of tornadoes and severe thunderstorms. The state is in the southeastern extension of Tornado Alley.',
    climate: 'Humid subtropical',
    roofingConsiderations: [
      'Tornado risk significant',
      'Severe thunderstorms with hail',
      'High humidity promotes algae',
      'Hot summers stress materials',
      'Ice storms occasionally',
    ],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Impact-Resistant Shingles', 'Asphalt Shingles'],
    averageCostRange: { low: 6500, high: 17000 },
    majorMetros: ['Little Rock', 'Fort Smith', 'Fayetteville', 'Springdale'],
    licensingInfo: 'Arkansas requires contractor licensing for projects over $20,000.',
    insuranceNotes: 'Storm and tornado damage covered. Impact-resistant materials may qualify for discounts.',
  },
  'iowa': {
    slug: 'iowa',
    name: 'Iowa',
    abbr: 'IA',
    description: 'Iowa has a humid continental climate with cold winters and hot summers. The state experiences severe thunderstorms, tornadoes, and significant hail damage.',
    climate: 'Humid continental',
    roofingConsiderations: [
      'Severe thunderstorms and tornado risk',
      'Hail damage very common',
      'Cold winters with heavy snow',
      'Ice dam prevention important',
      'Wide temperature swings',
    ],
    popularMaterials: ['Impact-Resistant Shingles', 'Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles'],
    averageCostRange: { low: 7000, high: 18500 },
    majorMetros: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Sioux City'],
    licensingInfo: 'Iowa does not require a state roofing license. Some cities have local requirements.',
    insuranceNotes: 'Hail claims extremely common. Impact-resistant materials may reduce premiums.',
  },
  'mississippi': {
    slug: 'mississippi',
    name: 'Mississippi',
    abbr: 'MS',
    description: 'Mississippi has a humid subtropical climate with hot summers and mild winters. The state faces hurricane risk along the Gulf Coast and tornado risk inland.',
    climate: 'Humid subtropical',
    roofingConsiderations: [
      'Hurricane risk in southern coastal areas',
      'Tornado risk inland',
      'High humidity promotes mold and algae',
      'Hot summers stress materials',
      'Heavy rainfall requires good drainage',
    ],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Hurricane-Rated Shingles', 'Asphalt Shingles'],
    averageCostRange: { low: 6500, high: 17000 },
    majorMetros: ['Jackson', 'Gulfport', 'Southaven', 'Biloxi'],
    licensingInfo: 'Mississippi requires residential contractor licensing through the State Board of Contractors.',
    insuranceNotes: 'Coastal areas have wind deductibles. Hurricane damage covered in most policies.',
  },
  'kansas': {
    slug: 'kansas',
    name: 'Kansas',
    abbr: 'KS',
    description: 'Kansas is in the heart of Tornado Alley with severe weather a major concern. Hail storms and high winds make impact-resistant roofing essential.',
    climate: 'Humid continental to semi-arid',
    roofingConsiderations: [
      'Very high tornado and hail risk',
      'Severe thunderstorms common',
      'High winds year-round',
      'Impact-resistant materials essential',
      'Hot summers and cold winters',
    ],
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Stone-Coated Steel', 'Architectural Shingles'],
    averageCostRange: { low: 7000, high: 18500 },
    majorMetros: ['Wichita', 'Overland Park', 'Kansas City', 'Topeka'],
    licensingInfo: 'Kansas does not require a state roofing license. Local requirements vary.',
    insuranceNotes: 'Impact-resistant shingles qualify for major discounts. Hail claims very frequent.',
  },
  'utah': {
    slug: 'utah',
    name: 'Utah',
    abbr: 'UT',
    description: 'Utah has a semi-arid climate with hot summers and snowy winters in mountain areas. The state requires roofing that handles UV exposure and occasional heavy snow.',
    climate: 'Semi-arid with mountain snow',
    roofingConsiderations: [
      'Heavy snow loads in mountain areas',
      'Intense UV exposure at altitude',
      'Desert heat in lower elevations',
      'Metal roofing popular for snow shedding',
      'Fire risk in some areas',
    ],
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Slate', 'Cool Roofing'],
    averageCostRange: { low: 8000, high: 22000 },
    majorMetros: ['Salt Lake City', 'West Valley City', 'Provo', 'West Jordan'],
    licensingInfo: 'Utah requires contractor licensing through the Division of Occupational and Professional Licensing.',
    insuranceNotes: 'Snow damage covered. Fire insurance important in mountain areas.',
  },
  'new-mexico': {
    slug: 'new-mexico',
    name: 'New Mexico',
    abbr: 'NM',
    description: 'New Mexico has a semi-arid to arid climate with intense sun exposure and monsoon rains. Flat roofs are common in traditional Southwestern architecture.',
    climate: 'Semi-arid to arid',
    roofingConsiderations: [
      'Intense UV exposure',
      'Monsoon storms bring heavy rain',
      'Flat roofs common in Southwest style',
      'High altitude stress on materials',
      'Fire risk in some areas',
    ],
    popularMaterials: ['Metal Roofing', 'Clay Tiles', 'TPO Flat Roofing', 'Cool Roofing'],
    averageCostRange: { low: 7500, high: 20000 },
    majorMetros: ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe'],
    licensingInfo: 'New Mexico requires contractor licensing through the Construction Industries Division.',
    insuranceNotes: 'Monsoon damage typically covered. Fire insurance important in forested areas.',
  },
  'nebraska': {
    slug: 'nebraska',
    name: 'Nebraska',
    abbr: 'NE',
    description: 'Nebraska has a continental climate with severe weather including tornadoes, hail, and blizzards. Impact-resistant roofing is highly recommended.',
    climate: 'Humid continental to semi-arid',
    roofingConsiderations: [
      'High tornado and hail risk',
      'Severe thunderstorms common',
      'Cold winters with heavy snow',
      'Wide temperature extremes',
      'Impact-resistant materials recommended',
    ],
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Architectural Shingles', 'Asphalt Shingles'],
    averageCostRange: { low: 7000, high: 18000 },
    majorMetros: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island'],
    licensingInfo: 'Nebraska does not require a state roofing license. Local requirements may apply.',
    insuranceNotes: 'Hail claims very common. Impact-resistant materials qualify for discounts.',
  },
  'west-virginia': {
    slug: 'west-virginia',
    name: 'West Virginia',
    abbr: 'WV',
    description: 'West Virginia has a humid continental climate with cold winters and warm summers. The mountainous terrain creates varied roofing conditions.',
    climate: 'Humid continental',
    roofingConsiderations: [
      'Heavy snow in mountain regions',
      'Ice dam formation common',
      'Steep terrain means steep roofs',
      'Mining areas may have settling issues',
      'High humidity promotes algae',
    ],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles', 'Slate'],
    averageCostRange: { low: 6500, high: 17000 },
    majorMetros: ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg'],
    licensingInfo: 'West Virginia requires contractor licensing through the Division of Labor.',
    insuranceNotes: 'Snow and ice damage covered. Mine subsidence coverage may be needed in some areas.',
  },
  'idaho': {
    slug: 'idaho',
    name: 'Idaho',
    abbr: 'ID',
    description: 'Idaho has diverse climates from semi-arid in the south to alpine conditions in the mountains. Heavy snow and fire risk are major considerations.',
    climate: 'Semi-arid to alpine',
    roofingConsiderations: [
      'Heavy snow loads in mountain areas',
      'Fire risk in forested regions',
      'Dry summers with intense sun',
      'Metal roofing popular for snow shedding',
      'Wide temperature variations',
    ],
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Fire-Resistant Materials', 'Asphalt Shingles'],
    averageCostRange: { low: 7500, high: 20000 },
    majorMetros: ['Boise', 'Meridian', 'Nampa', 'Idaho Falls'],
    licensingInfo: 'Idaho requires contractor licensing through the Division of Building Safety.',
    insuranceNotes: 'Fire insurance critical in many areas. Snow damage covered.',
  },
  'maine': {
    slug: 'maine',
    name: 'Maine',
    abbr: 'ME',
    description: 'Maine has a humid continental climate with harsh winters featuring heavy snow and ice. The state has many historic homes and coastal properties.',
    climate: 'Humid continental with harsh winters',
    roofingConsiderations: [
      'Heavy snow and ice accumulation',
      'Ice dam prevention critical',
      'Coastal areas face salt and wind',
      'Short roofing season',
      'Historic home preservation',
    ],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Cedar Shakes', 'Slate'],
    averageCostRange: { low: 8000, high: 22000 },
    majorMetros: ['Portland', 'Lewiston', 'Bangor', 'South Portland'],
    licensingInfo: 'Maine does not require a state roofing license. Local requirements may apply.',
    insuranceNotes: 'Ice dam coverage important. Coastal wind damage covered.',
  },
  'new-hampshire': {
    slug: 'new-hampshire',
    name: 'New Hampshire',
    abbr: 'NH',
    description: 'New Hampshire experiences harsh New England winters with significant snow and ice. The White Mountains see some of the worst weather in the country.',
    climate: 'Humid continental with harsh winters',
    roofingConsiderations: [
      'Extreme snow loads in mountains',
      'Ice dam formation common',
      'Nor\'easters bring heavy precipitation',
      'Short construction season',
      'Historic properties require special materials',
    ],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Slate', 'Cedar Shakes'],
    averageCostRange: { low: 8500, high: 24000 },
    majorMetros: ['Manchester', 'Nashua', 'Concord', 'Dover'],
    licensingInfo: 'New Hampshire does not require a state roofing license. Local requirements vary.',
    insuranceNotes: 'Ice dam and snow damage coverage important. Wind damage from storms covered.',
  },
  'montana': {
    slug: 'montana',
    name: 'Montana',
    abbr: 'MT',
    description: 'Montana has a diverse climate from semi-arid plains to alpine mountains. Heavy snow, extreme cold, and fire risk are major roofing considerations.',
    climate: 'Semi-arid to alpine',
    roofingConsiderations: [
      'Extreme cold and heavy snow',
      'Fire risk in forested areas',
      'Chinook winds cause temperature swings',
      'Short construction season',
      'Metal roofing popular for snow',
    ],
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Fire-Resistant Materials', 'Asphalt Shingles'],
    averageCostRange: { low: 7500, high: 20000 },
    majorMetros: ['Billings', 'Missoula', 'Great Falls', 'Bozeman'],
    licensingInfo: 'Montana requires contractor registration with the Department of Labor and Industry.',
    insuranceNotes: 'Fire insurance essential in many areas. Snow and ice damage covered.',
  },
  'rhode-island': {
    slug: 'rhode-island',
    name: 'Rhode Island',
    abbr: 'RI',
    description: 'Rhode Island has a humid continental climate with coastal influences. The state experiences nor\'easters, hurricanes, and winter storms.',
    climate: 'Humid continental with coastal influence',
    roofingConsiderations: [
      'Hurricane and nor\'easter risk',
      'Salt air corrosion on coast',
      'Snow and ice in winter',
      'Historic preservation requirements',
      'Wind-resistant materials important',
    ],
    popularMaterials: ['Architectural Shingles', 'Slate', 'Metal Roofing', 'Cedar Shakes'],
    averageCostRange: { low: 8500, high: 24000 },
    majorMetros: ['Providence', 'Warwick', 'Cranston', 'Pawtucket'],
    licensingInfo: 'Rhode Island requires contractor registration through the Contractors\' Registration Board.',
    insuranceNotes: 'Coastal wind deductibles may apply. Hurricane damage typically covered.',
  },
  'delaware': {
    slug: 'delaware',
    name: 'Delaware',
    abbr: 'DE',
    description: 'Delaware has a humid subtropical climate with hot summers and mild winters. Coastal areas face hurricane risk while the entire state experiences nor\'easters.',
    climate: 'Humid subtropical',
    roofingConsiderations: [
      'Hurricane risk on the coast',
      'Nor\'easters bring wind and rain',
      'High humidity promotes algae',
      'Salt air near beaches',
      'Moderate four-season climate inland',
    ],
    popularMaterials: ['Architectural Shingles', 'Metal Roofing', 'Asphalt Shingles', 'Flat Roofing'],
    averageCostRange: { low: 7500, high: 21000 },
    majorMetros: ['Wilmington', 'Dover', 'Newark', 'Middletown'],
    licensingInfo: 'Delaware requires contractor licensing through the Division of Professional Regulation.',
    insuranceNotes: 'Coastal areas have wind deductibles. Hurricane and storm damage covered.',
  },
  'south-dakota': {
    slug: 'south-dakota',
    name: 'South Dakota',
    abbr: 'SD',
    description: 'South Dakota has a continental climate with severe weather including blizzards, tornadoes, and hail. Impact-resistant roofing is highly recommended.',
    climate: 'Continental with severe weather',
    roofingConsiderations: [
      'Severe hail and tornado risk',
      'Heavy snow and blizzards',
      'Extreme temperature swings',
      'High winds common',
      'Impact-resistant materials essential',
    ],
    popularMaterials: ['Impact-Resistant Shingles', 'Metal Roofing', 'Architectural Shingles', 'Asphalt Shingles'],
    averageCostRange: { low: 7000, high: 18000 },
    majorMetros: ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Brookings'],
    licensingInfo: 'South Dakota does not require a state roofing license. Local requirements may apply.',
    insuranceNotes: 'Hail damage claims common. Impact-resistant materials qualify for discounts.',
  },
  'north-dakota': {
    slug: 'north-dakota',
    name: 'North Dakota',
    abbr: 'ND',
    description: 'North Dakota has a harsh continental climate with extreme cold, heavy snow, and severe summer storms including hail and tornadoes.',
    climate: 'Continental with extreme winters',
    roofingConsiderations: [
      'Extreme cold and heavy snow',
      'Hail and tornado risk in summer',
      'Very short construction season',
      'Ice dam prevention critical',
      'Impact-resistant materials recommended',
    ],
    popularMaterials: ['Metal Roofing', 'Impact-Resistant Shingles', 'Architectural Shingles', 'EPDM'],
    averageCostRange: { low: 7500, high: 19000 },
    majorMetros: ['Fargo', 'Bismarck', 'Grand Forks', 'Minot'],
    licensingInfo: 'North Dakota requires contractor licensing through the Secretary of State.',
    insuranceNotes: 'Hail claims common. Ice dam and winter damage covered.',
  },
  'vermont': {
    slug: 'vermont',
    name: 'Vermont',
    abbr: 'VT',
    description: 'Vermont has a humid continental climate with cold, snowy winters and warm summers. The state has many historic buildings and strict environmental standards.',
    climate: 'Humid continental with harsh winters',
    roofingConsiderations: [
      'Heavy snow loads',
      'Ice dam formation common',
      'Short construction season',
      'Historic preservation important',
      'Environmental regulations strict',
    ],
    popularMaterials: ['Metal Roofing', 'Architectural Shingles', 'Slate', 'Cedar Shakes'],
    averageCostRange: { low: 8000, high: 23000 },
    majorMetros: ['Burlington', 'South Burlington', 'Rutland', 'Barre'],
    licensingInfo: 'Vermont requires contractor registration with the Secretary of State.',
    insuranceNotes: 'Ice dam coverage important. Snow damage covered by standard policies.',
  },
  'wyoming': {
    slug: 'wyoming',
    name: 'Wyoming',
    abbr: 'WY',
    description: 'Wyoming has a semi-arid continental climate with harsh winters, high winds, and significant snowfall in mountain areas. Wind-resistant roofing is essential.',
    climate: 'Semi-arid continental',
    roofingConsiderations: [
      'Very high winds year-round',
      'Heavy snow in mountain areas',
      'Extreme cold in winter',
      'Hail damage risk',
      'Short construction season',
    ],
    popularMaterials: ['Metal Roofing', 'Impact-Resistant Shingles', 'Architectural Shingles', 'Stone-Coated Steel'],
    averageCostRange: { low: 7500, high: 20000 },
    majorMetros: ['Cheyenne', 'Casper', 'Laramie', 'Gillette'],
    licensingInfo: 'Wyoming does not require a state roofing license. Local requirements may apply.',
    insuranceNotes: 'Wind damage claims common. Hail and snow damage covered.',
  },
};

// Get state data by slug
export function getStateBySlug(slug: string): StateData | undefined {
  return stateData[slug];
}

// Get all state slugs
export function getAllStateSlugs(): string[] {
  return Object.keys(stateData);
}

// Get cities in a state
export function getCitiesInStateBySlug(stateSlug: string): LocationData[] {
  const state = stateData[stateSlug];
  if (!state) return [];

  return locations.filter(loc => loc.stateAbbr === state.abbr);
}

// Format state name for URL
export function stateNameToSlug(stateName: string): string {
  return stateName.toLowerCase().replace(/\s+/g, '-');
}
