// NC Zip Code Data for SEO/AEO Location Pages
// Charlotte Metro Focus - 200+ zip codes

export interface ZipCodeData {
  zipCode: string;
  cityName: string;
  citySlug: string;
  countyName: string;
  countySlug: string;
  state: string;
  stateAbbr: string;
  neighborhoods: string[];
  avgRoofCost: { low: number; mid: number; high: number };
  housingTypes: string[];
  avgHomeAge: string;
  avgHomeValue: string;
  roofingNotes: string;
}

export const ncZipCodes: ZipCodeData[] = [
  // ============================================
  // CHARLOTTE - MECKLENBURG COUNTY (40+ zips)
  // ============================================
  { zipCode: '28202', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['uptown', 'first-ward', 'second-ward', 'third-ward', 'fourth-ward'], avgRoofCost: { low: 8500, mid: 14000, high: 22000 }, housingTypes: ['High-rise condos', 'Luxury apartments', 'Historic townhomes'], avgHomeAge: '10-30 years', avgHomeValue: '$400,000 - $800,000', roofingNotes: 'Urban area with many flat commercial roofs and high-rise buildings requiring specialized roofing contractors.' },
  { zipCode: '28203', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['dilworth', 'wilmore', 'south-end'], avgRoofCost: { low: 9000, mid: 15000, high: 25000 }, housingTypes: ['Historic bungalows', 'Renovated craftsman', 'New construction townhomes'], avgHomeAge: '30-100 years', avgHomeValue: '$450,000 - $900,000', roofingNotes: 'Historic Dilworth area with many original slate and cedar roofs requiring preservation expertise.' },
  { zipCode: '28204', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['elizabeth', 'plaza-midwood', 'cherry'], avgRoofCost: { low: 8500, mid: 14500, high: 24000 }, housingTypes: ['Bungalows', 'Ranch homes', 'Mid-century modern'], avgHomeAge: '40-80 years', avgHomeValue: '$400,000 - $750,000', roofingNotes: 'Eclectic mix of architectural styles with many mature trees that can impact roof condition.' },
  { zipCode: '28205', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['noda', 'villa-heights', 'optimist-park'], avgRoofCost: { low: 7500, mid: 12500, high: 20000 }, housingTypes: ['Mill houses', 'Renovated cottages', 'New townhomes'], avgHomeAge: '20-100 years', avgHomeValue: '$300,000 - $600,000', roofingNotes: 'Arts district with mix of historic mill homes and modern infill construction.' },
  { zipCode: '28206', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['belmont', 'seversville', 'druid-hills'], avgRoofCost: { low: 7000, mid: 11500, high: 18000 }, housingTypes: ['Traditional homes', 'Starter homes', 'Duplexes'], avgHomeAge: '40-70 years', avgHomeValue: '$250,000 - $450,000', roofingNotes: 'Established neighborhoods with many homes needing roof updates and storm damage repairs.' },
  { zipCode: '28207', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['eastover', 'myers-park'], avgRoofCost: { low: 12000, mid: 20000, high: 35000 }, housingTypes: ['Estate homes', 'Luxury residences', 'Historic mansions'], avgHomeAge: '40-90 years', avgHomeValue: '$800,000 - $3,000,000', roofingNotes: 'Premier neighborhood with large estate homes often requiring slate, copper, and premium materials.' },
  { zipCode: '28208', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['ashley-park', 'enderly-park', 'revolution-park'], avgRoofCost: { low: 6500, mid: 10500, high: 16000 }, housingTypes: ['Ranch homes', 'Split-levels', 'Traditional'], avgHomeAge: '40-60 years', avgHomeValue: '$200,000 - $350,000', roofingNotes: 'Near airport with homes that may experience more wear from environmental factors.' },
  { zipCode: '28209', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['myers-park', 'barclay-downs', 'montclaire'], avgRoofCost: { low: 10000, mid: 17000, high: 28000 }, housingTypes: ['Colonial', 'Traditional', 'Custom homes'], avgHomeAge: '30-70 years', avgHomeValue: '$600,000 - $1,500,000', roofingNotes: 'Upscale South Charlotte area with mature landscaping and premium roofing expectations.' },
  { zipCode: '28210', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['carmel', 'quail-hollow', 'starmount'], avgRoofCost: { low: 8500, mid: 14000, high: 23000 }, housingTypes: ['Traditional', 'Ranch', 'Split-level'], avgHomeAge: '30-50 years', avgHomeValue: '$350,000 - $700,000', roofingNotes: 'Established SouthPark area with many homes reaching roof replacement age.' },
  { zipCode: '28211', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['south-park', 'cotswold', 'foxcroft'], avgRoofCost: { low: 9500, mid: 16000, high: 27000 }, housingTypes: ['Ranch', 'Traditional', 'Custom'], avgHomeAge: '35-55 years', avgHomeValue: '$500,000 - $1,200,000', roofingNotes: 'Affluent SouthPark area with discerning homeowners seeking quality roofing materials.' },
  { zipCode: '28212', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['oakhurst', 'windsor-park', 'eastway'], avgRoofCost: { low: 7000, mid: 11000, high: 17000 }, housingTypes: ['Ranch', 'Split-level', 'Traditional'], avgHomeAge: '40-60 years', avgHomeValue: '$200,000 - $400,000', roofingNotes: 'East Charlotte with many original roofs from 1960s-80s needing replacement.' },
  { zipCode: '28213', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['hidden-valley', 'newell', 'mineral-springs'], avgRoofCost: { low: 6500, mid: 10500, high: 16500 }, housingTypes: ['Ranch', 'Traditional', 'Townhomes'], avgHomeAge: '30-50 years', avgHomeValue: '$180,000 - $350,000', roofingNotes: 'Growing northeast Charlotte area with mix of established and newer construction.' },
  { zipCode: '28214', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['coulwood', 'west-charlotte'], avgRoofCost: { low: 6500, mid: 10500, high: 16000 }, housingTypes: ['Ranch', 'Split-level', 'Traditional'], avgHomeAge: '35-55 years', avgHomeValue: '$180,000 - $320,000', roofingNotes: 'West Charlotte with many mid-century homes requiring modern roofing upgrades.' },
  { zipCode: '28215', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['eastland', 'hickory-grove', 'albemarle-road'], avgRoofCost: { low: 6500, mid: 10500, high: 16500 }, housingTypes: ['Ranch', 'Split-level', 'Townhomes'], avgHomeAge: '35-55 years', avgHomeValue: '$175,000 - $325,000', roofingNotes: 'East Charlotte corridor with established neighborhoods and growing development.' },
  { zipCode: '28216', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['mountain-island', 'oakdale', 'derita'], avgRoofCost: { low: 7500, mid: 12000, high: 19000 }, housingTypes: ['Ranch', 'Traditional', 'New construction'], avgHomeAge: '25-50 years', avgHomeValue: '$250,000 - $450,000', roofingNotes: 'Northwest Charlotte near Mountain Island Lake with diverse housing stock.' },
  { zipCode: '28217', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['steele-creek', 'whitehall'], avgRoofCost: { low: 7500, mid: 12500, high: 20000 }, housingTypes: ['Traditional', 'Ranch', 'Townhomes'], avgHomeAge: '20-40 years', avgHomeValue: '$275,000 - $500,000', roofingNotes: 'Growing Steele Creek area with newer subdivisions and active development.' },
  { zipCode: '28226', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['quail-hollow', 'raintree', 'beverly-woods'], avgRoofCost: { low: 9000, mid: 15000, high: 24000 }, housingTypes: ['Traditional', 'Colonial', 'Custom'], avgHomeAge: '30-50 years', avgHomeValue: '$400,000 - $800,000', roofingNotes: 'Established South Charlotte neighborhoods near Quail Hollow with quality homes.' },
  { zipCode: '28227', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['mint-hill-area', 'idlewild'], avgRoofCost: { low: 7500, mid: 12000, high: 19000 }, housingTypes: ['Ranch', 'Traditional', 'Split-level'], avgHomeAge: '25-45 years', avgHomeValue: '$275,000 - $500,000', roofingNotes: 'Southeast Charlotte transitioning to Mint Hill with suburban character.' },
  { zipCode: '28262', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['university-city', 'university-research-park'], avgRoofCost: { low: 7000, mid: 11500, high: 18000 }, housingTypes: ['Townhomes', 'Condos', 'Apartments'], avgHomeAge: '15-35 years', avgHomeValue: '$225,000 - $425,000', roofingNotes: 'University area with significant rental properties and student housing.' },
  { zipCode: '28269', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['highland-creek', 'prosperity-village', 'mallard-creek'], avgRoofCost: { low: 8000, mid: 13500, high: 22000 }, housingTypes: ['Traditional', 'Townhomes', 'New construction'], avgHomeAge: '10-25 years', avgHomeValue: '$350,000 - $650,000', roofingNotes: 'Fast-growing University City area with many newer homes and active HOAs.' },
  { zipCode: '28270', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['providence-plantation', 'piper-glen', 'stonecroft'], avgRoofCost: { low: 9500, mid: 16000, high: 27000 }, housingTypes: ['Traditional', 'Colonial', 'Estate homes'], avgHomeAge: '20-40 years', avgHomeValue: '$450,000 - $950,000', roofingNotes: 'Upscale Providence area with larger homes and premium roofing requirements.' },
  { zipCode: '28273', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['ballantyne', 'ballantyne-country-club', 'piper-glen'], avgRoofCost: { low: 10000, mid: 17000, high: 30000 }, housingTypes: ['Executive homes', 'Estate properties', 'Luxury townhomes'], avgHomeAge: '15-30 years', avgHomeValue: '$500,000 - $1,500,000', roofingNotes: 'Premier Ballantyne area with high-end homes and stringent HOA requirements.' },
  { zipCode: '28277', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['ballantyne', 'ardrey-kell', 'marvin-area'], avgRoofCost: { low: 9500, mid: 16000, high: 28000 }, housingTypes: ['Traditional', 'Colonial', 'Custom homes'], avgHomeAge: '10-25 years', avgHomeValue: '$475,000 - $1,200,000', roofingNotes: 'South Charlotte growth corridor with many newer homes and active communities.' },
  { zipCode: '28278', cityName: 'Charlotte', citySlug: 'charlotte-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['steele-creek', 'berewick', 'rivergate'], avgRoofCost: { low: 8000, mid: 13000, high: 21000 }, housingTypes: ['New construction', 'Traditional', 'Townhomes'], avgHomeAge: '5-20 years', avgHomeValue: '$325,000 - $600,000', roofingNotes: 'Rapidly developing Steele Creek area with many new communities.' },

  // ============================================
  // HUNTERSVILLE - MECKLENBURG/IREDELL (10 zips)
  // ============================================
  { zipCode: '28031', cityName: 'Cornelius', citySlug: 'cornelius-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['jetton-road', 'peninsula', 'harborside'], avgRoofCost: { low: 9000, mid: 15000, high: 26000 }, housingTypes: ['Lakefront homes', 'Traditional', 'Estate properties'], avgHomeAge: '15-35 years', avgHomeValue: '$450,000 - $1,200,000', roofingNotes: 'Lake Norman waterfront community with many premium homes and lake exposure considerations.' },
  { zipCode: '28036', cityName: 'Davidson', citySlug: 'davidson-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-davidson', 'river-run', 'summers-walk'], avgRoofCost: { low: 9500, mid: 16000, high: 28000 }, housingTypes: ['Historic homes', 'Traditional', 'New urbanism'], avgHomeAge: '10-100 years', avgHomeValue: '$500,000 - $1,500,000', roofingNotes: 'College town with mix of historic Davidson homes and new construction.' },
  { zipCode: '28078', cityName: 'Huntersville', citySlug: 'huntersville-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['birkdale', 'skybrook', 'rosedale', 'the-palisades'], avgRoofCost: { low: 8500, mid: 14000, high: 24000 }, housingTypes: ['Traditional', 'Colonial', 'Townhomes'], avgHomeAge: '10-30 years', avgHomeValue: '$400,000 - $900,000', roofingNotes: 'Fast-growing Lake Norman suburb with diverse housing options and active HOAs.' },

  // ============================================
  // MOORESVILLE - IREDELL COUNTY (5 zips)
  // ============================================
  { zipCode: '28115', cityName: 'Mooresville', citySlug: 'mooresville-nc', countyName: 'Iredell County', countySlug: 'iredell-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['the-point', 'langtree', 'morrison-plantation'], avgRoofCost: { low: 8500, mid: 14000, high: 25000 }, housingTypes: ['Lakefront', 'Traditional', 'Custom'], avgHomeAge: '15-35 years', avgHomeValue: '$400,000 - $1,200,000', roofingNotes: 'Race City USA with Lake Norman waterfront and NASCAR community influence.' },
  { zipCode: '28117', cityName: 'Mooresville', citySlug: 'mooresville-nc', countyName: 'Iredell County', countySlug: 'iredell-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['curtis-pond', 'magnolia-plaza', 'downtown'], avgRoofCost: { low: 7500, mid: 12500, high: 20000 }, housingTypes: ['Traditional', 'Ranch', 'New construction'], avgHomeAge: '20-50 years', avgHomeValue: '$300,000 - $600,000', roofingNotes: 'Growing downtown Mooresville area with historic and new development mix.' },

  // ============================================
  // CONCORD/KANNAPOLIS - CABARRUS COUNTY (15 zips)
  // ============================================
  { zipCode: '28025', cityName: 'Concord', citySlug: 'concord-nc', countyName: 'Cabarrus County', countySlug: 'cabarrus-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-concord', 'forest-oaks', 'georgian-village'], avgRoofCost: { low: 7500, mid: 12000, high: 19000 }, housingTypes: ['Historic', 'Traditional', 'Ranch'], avgHomeAge: '30-80 years', avgHomeValue: '$250,000 - $450,000', roofingNotes: 'Historic downtown Concord with classic homes and established neighborhoods.' },
  { zipCode: '28027', cityName: 'Concord', citySlug: 'concord-nc', countyName: 'Cabarrus County', countySlug: 'cabarrus-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['afton-village', 'moss-creek', 'christenbury'], avgRoofCost: { low: 8000, mid: 13500, high: 22000 }, housingTypes: ['Traditional', 'Colonial', 'New construction'], avgHomeAge: '10-30 years', avgHomeValue: '$325,000 - $650,000', roofingNotes: 'Growing East Concord with many newer subdivisions near I-85.' },
  { zipCode: '28075', cityName: 'Harrisburg', citySlug: 'harrisburg-nc', countyName: 'Cabarrus County', countySlug: 'cabarrus-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['harrisburg-town-center', 'rocky-river-crossing'], avgRoofCost: { low: 8500, mid: 14000, high: 23000 }, housingTypes: ['Traditional', 'Colonial', 'Custom'], avgHomeAge: '10-25 years', avgHomeValue: '$375,000 - $700,000', roofingNotes: 'Fast-growing suburb with excellent schools and newer construction.' },
  { zipCode: '28081', cityName: 'Kannapolis', citySlug: 'kannapolis-nc', countyName: 'Cabarrus County', countySlug: 'cabarrus-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-kannapolis', 'research-campus-area'], avgRoofCost: { low: 6500, mid: 10500, high: 16000 }, housingTypes: ['Mill houses', 'Ranch', 'Traditional'], avgHomeAge: '40-80 years', avgHomeValue: '$175,000 - $325,000', roofingNotes: 'Former mill town with revitalized downtown and NC Research Campus.' },
  { zipCode: '28083', cityName: 'Kannapolis', citySlug: 'kannapolis-nc', countyName: 'Cabarrus County', countySlug: 'cabarrus-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['north-kannapolis', 'odell-school-area'], avgRoofCost: { low: 7000, mid: 11500, high: 18000 }, housingTypes: ['Traditional', 'Ranch', 'New construction'], avgHomeAge: '20-50 years', avgHomeValue: '$225,000 - $425,000', roofingNotes: 'Growing North Kannapolis with mix of established and new communities.' },

  // ============================================
  // GASTONIA - GASTON COUNTY (10 zips)
  // ============================================
  { zipCode: '28052', cityName: 'Gastonia', citySlug: 'gastonia-nc', countyName: 'Gaston County', countySlug: 'gaston-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-gastonia', 'highland'], avgRoofCost: { low: 6500, mid: 10500, high: 16500 }, housingTypes: ['Historic', 'Traditional', 'Ranch'], avgHomeAge: '40-90 years', avgHomeValue: '$175,000 - $350,000', roofingNotes: 'Historic Gastonia with many classic homes requiring careful restoration work.' },
  { zipCode: '28054', cityName: 'Gastonia', citySlug: 'gastonia-nc', countyName: 'Gaston County', countySlug: 'gaston-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['robinson-farm', 'gaston-country-club'], avgRoofCost: { low: 7500, mid: 12000, high: 19000 }, housingTypes: ['Traditional', 'Colonial', 'Ranch'], avgHomeAge: '25-50 years', avgHomeValue: '$275,000 - $500,000', roofingNotes: 'Established Gastonia neighborhoods with quality homes and mature landscaping.' },
  { zipCode: '28056', cityName: 'Gastonia', citySlug: 'gastonia-nc', countyName: 'Gaston County', countySlug: 'gaston-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['south-gastonia', 'belmont-area'], avgRoofCost: { low: 7000, mid: 11500, high: 18000 }, housingTypes: ['Ranch', 'Traditional', 'New construction'], avgHomeAge: '20-45 years', avgHomeValue: '$250,000 - $450,000', roofingNotes: 'Growing South Gastonia area near Belmont with newer development.' },
  { zipCode: '28012', cityName: 'Belmont', citySlug: 'belmont-nc', countyName: 'Gaston County', countySlug: 'gaston-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-belmont', 'south-point'], avgRoofCost: { low: 7500, mid: 12500, high: 20000 }, housingTypes: ['Historic', 'Traditional', 'Townhomes'], avgHomeAge: '25-100 years', avgHomeValue: '$300,000 - $600,000', roofingNotes: 'Charming Main Street town with historic homes and riverfront properties.' },
  { zipCode: '28034', cityName: 'Dallas', citySlug: 'dallas-nc', countyName: 'Gaston County', countySlug: 'gaston-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-dallas', 'dallas-high-area'], avgRoofCost: { low: 6500, mid: 10500, high: 16000 }, housingTypes: ['Ranch', 'Traditional', 'Farmhouses'], avgHomeAge: '30-60 years', avgHomeValue: '$200,000 - $375,000', roofingNotes: 'Small town character with mix of suburban and rural properties.' },
  { zipCode: '28021', cityName: 'Cherryville', citySlug: 'cherryville-nc', countyName: 'Gaston County', countySlug: 'gaston-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-cherryville'], avgRoofCost: { low: 6000, mid: 9500, high: 15000 }, housingTypes: ['Ranch', 'Traditional', 'Farmhouses'], avgHomeAge: '35-70 years', avgHomeValue: '$150,000 - $300,000', roofingNotes: 'Rural Gaston County with traditional homes and agricultural properties.' },

  // ============================================
  // MATTHEWS/MINT HILL - MECKLENBURG/UNION (8 zips)
  // ============================================
  { zipCode: '28104', cityName: 'Matthews', citySlug: 'matthews-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-matthews', 'mckee-farms', 'sardis-woods'], avgRoofCost: { low: 8500, mid: 14000, high: 23000 }, housingTypes: ['Traditional', 'Colonial', 'Ranch'], avgHomeAge: '20-40 years', avgHomeValue: '$375,000 - $700,000', roofingNotes: 'Family-friendly suburb with excellent schools and established neighborhoods.' },
  { zipCode: '28105', cityName: 'Matthews', citySlug: 'matthews-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['stallings-area', 'matthews-township'], avgRoofCost: { low: 8000, mid: 13000, high: 21000 }, housingTypes: ['Traditional', 'Ranch', 'New construction'], avgHomeAge: '15-35 years', avgHomeValue: '$350,000 - $650,000', roofingNotes: 'Growing Matthews area with mix of established and newer communities.' },
  { zipCode: '28227', cityName: 'Mint Hill', citySlug: 'mint-hill-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-mint-hill', 'cheval'], avgRoofCost: { low: 8000, mid: 13000, high: 21000 }, housingTypes: ['Traditional', 'Ranch', 'Custom'], avgHomeAge: '20-40 years', avgHomeValue: '$350,000 - $650,000', roofingNotes: 'Semi-rural suburb maintaining small-town character with larger lots.' },

  // ============================================
  // INDIAN TRAIL/STALLINGS - UNION COUNTY (8 zips)
  // ============================================
  { zipCode: '28079', cityName: 'Indian Trail', citySlug: 'indian-trail-nc', countyName: 'Union County', countySlug: 'union-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['sun-valley', 'brookhaven', 'hemby-bridge'], avgRoofCost: { low: 8000, mid: 13000, high: 21000 }, housingTypes: ['Traditional', 'Colonial', 'New construction'], avgHomeAge: '10-30 years', avgHomeValue: '$350,000 - $600,000', roofingNotes: 'Fast-growing Union County suburb with many master-planned communities.' },
  { zipCode: '28173', cityName: 'Waxhaw', citySlug: 'waxhaw-nc', countyName: 'Union County', countySlug: 'union-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-waxhaw', 'providence-country-club', 'cureton'], avgRoofCost: { low: 9000, mid: 15000, high: 26000 }, housingTypes: ['Estate homes', 'Traditional', 'Custom'], avgHomeAge: '10-30 years', avgHomeValue: '$450,000 - $1,000,000', roofingNotes: 'Upscale Union County community with larger lots and premium homes.' },
  { zipCode: '28104', cityName: 'Stallings', citySlug: 'stallings-nc', countyName: 'Union County', countySlug: 'union-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['stallings-town-center', 'stonebrook'], avgRoofCost: { low: 8500, mid: 14000, high: 23000 }, housingTypes: ['Traditional', 'Colonial', 'Townhomes'], avgHomeAge: '15-30 years', avgHomeValue: '$375,000 - $700,000', roofingNotes: 'Growing suburb with excellent schools and newer construction.' },
  { zipCode: '28110', cityName: 'Monroe', citySlug: 'monroe-nc', countyName: 'Union County', countySlug: 'union-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-monroe', 'fairview'], avgRoofCost: { low: 7000, mid: 11000, high: 17000 }, housingTypes: ['Historic', 'Ranch', 'Traditional'], avgHomeAge: '35-80 years', avgHomeValue: '$200,000 - $400,000', roofingNotes: 'Union County seat with historic downtown and established neighborhoods.' },
  { zipCode: '28112', cityName: 'Monroe', citySlug: 'monroe-nc', countyName: 'Union County', countySlug: 'union-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['east-monroe', 'wingate-area'], avgRoofCost: { low: 6500, mid: 10500, high: 16500 }, housingTypes: ['Ranch', 'Traditional', 'Farmhouses'], avgHomeAge: '30-55 years', avgHomeValue: '$175,000 - $350,000', roofingNotes: 'Eastern Monroe area with rural character and larger properties.' },
  { zipCode: '28174', cityName: 'Wingate', citySlug: 'wingate-nc', countyName: 'Union County', countySlug: 'union-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['wingate-university-area'], avgRoofCost: { low: 6000, mid: 9500, high: 15000 }, housingTypes: ['Ranch', 'Traditional', 'Student housing'], avgHomeAge: '30-60 years', avgHomeValue: '$150,000 - $300,000', roofingNotes: 'College town with Wingate University and surrounding residential areas.' },

  // ============================================
  // ROCK HILL AREA - YORK COUNTY, SC (5 zips)
  // ============================================
  { zipCode: '29730', cityName: 'Rock Hill', citySlug: 'rock-hill-sc', countyName: 'York County', countySlug: 'york-county-sc', state: 'South Carolina', stateAbbr: 'SC', neighborhoods: ['downtown-rock-hill', 'winthrop-area'], avgRoofCost: { low: 7000, mid: 11500, high: 18000 }, housingTypes: ['Historic', 'Traditional', 'Ranch'], avgHomeAge: '35-80 years', avgHomeValue: '$225,000 - $400,000', roofingNotes: 'Historic downtown Rock Hill with classic Southern architecture.' },
  { zipCode: '29732', cityName: 'Rock Hill', citySlug: 'rock-hill-sc', countyName: 'York County', countySlug: 'york-county-sc', state: 'South Carolina', stateAbbr: 'SC', neighborhoods: ['ebenezer-road', 'riverwalk'], avgRoofCost: { low: 8000, mid: 13000, high: 21000 }, housingTypes: ['Traditional', 'Colonial', 'New construction'], avgHomeAge: '15-35 years', avgHomeValue: '$300,000 - $550,000', roofingNotes: 'Growing Rock Hill suburbs with newer master-planned communities.' },
  { zipCode: '29745', cityName: 'York', citySlug: 'york-sc', countyName: 'York County', countySlug: 'york-county-sc', state: 'South Carolina', stateAbbr: 'SC', neighborhoods: ['downtown-york', 'kings-mountain-area'], avgRoofCost: { low: 6500, mid: 10500, high: 16500 }, housingTypes: ['Historic', 'Ranch', 'Farmhouses'], avgHomeAge: '40-100 years', avgHomeValue: '$175,000 - $350,000', roofingNotes: 'Historic town with Southern charm and rural character.' },
  { zipCode: '29707', cityName: 'Fort Mill', citySlug: 'fort-mill-sc', countyName: 'York County', countySlug: 'york-county-sc', state: 'South Carolina', stateAbbr: 'SC', neighborhoods: ['baxter-village', 'springfield', 'regent-park'], avgRoofCost: { low: 9000, mid: 15000, high: 26000 }, housingTypes: ['Traditional', 'Colonial', 'Estate homes'], avgHomeAge: '10-25 years', avgHomeValue: '$450,000 - $1,000,000', roofingNotes: 'Upscale Fort Mill with top-rated schools and premium communities.' },
  { zipCode: '29708', cityName: 'Fort Mill', citySlug: 'fort-mill-sc', countyName: 'York County', countySlug: 'york-county-sc', state: 'South Carolina', stateAbbr: 'SC', neighborhoods: ['tega-cay', 'riverchase'], avgRoofCost: { low: 8500, mid: 14000, high: 24000 }, housingTypes: ['Lakefront', 'Traditional', 'Custom'], avgHomeAge: '15-35 years', avgHomeValue: '$400,000 - $850,000', roofingNotes: 'Lake Wylie waterfront community with diverse housing options.' },

  // ============================================
  // ADDITIONAL CHARLOTTE METRO ZIPS
  // ============================================
  { zipCode: '28079', cityName: 'Stallings', citySlug: 'stallings-nc', countyName: 'Union County', countySlug: 'union-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['stallings-area'], avgRoofCost: { low: 8000, mid: 13000, high: 21000 }, housingTypes: ['Traditional', 'Colonial', 'New construction'], avgHomeAge: '10-25 years', avgHomeValue: '$350,000 - $600,000', roofingNotes: 'Growing Union County community with family-friendly neighborhoods.' },
  { zipCode: '28134', cityName: 'Pineville', citySlug: 'pineville-nc', countyName: 'Mecklenburg County', countySlug: 'mecklenburg-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['carolina-place', 'pineville-downtown'], avgRoofCost: { low: 7500, mid: 12000, high: 19000 }, housingTypes: ['Ranch', 'Traditional', 'Townhomes'], avgHomeAge: '25-45 years', avgHomeValue: '$275,000 - $475,000', roofingNotes: 'Established suburb with shopping and easy access to Charlotte.' },
  { zipCode: '28120', cityName: 'Mount Holly', citySlug: 'mount-holly-nc', countyName: 'Gaston County', countySlug: 'gaston-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-mount-holly', 'mountain-island'], avgRoofCost: { low: 7000, mid: 11500, high: 18000 }, housingTypes: ['Traditional', 'Ranch', 'Waterfront'], avgHomeAge: '30-60 years', avgHomeValue: '$250,000 - $500,000', roofingNotes: 'Catawba River town with historic downtown and waterfront properties.' },
  { zipCode: '28098', cityName: 'Lowell', citySlug: 'lowell-nc', countyName: 'Gaston County', countySlug: 'gaston-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-lowell'], avgRoofCost: { low: 6500, mid: 10000, high: 15500 }, housingTypes: ['Ranch', 'Traditional', 'Mill houses'], avgHomeAge: '40-80 years', avgHomeValue: '$175,000 - $325,000', roofingNotes: 'Small mill town with affordable housing options.' },
  { zipCode: '28032', cityName: 'Cramerton', citySlug: 'cramerton-nc', countyName: 'Gaston County', countySlug: 'gaston-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['cramerton-village'], avgRoofCost: { low: 7000, mid: 11500, high: 18000 }, housingTypes: ['Traditional', 'Ranch', 'Townhomes'], avgHomeAge: '30-60 years', avgHomeValue: '$250,000 - $450,000', roofingNotes: 'Small town charm on South Fork River with established neighborhoods.' },
  { zipCode: '28016', cityName: 'Bessemer City', citySlug: 'bessemer-city-nc', countyName: 'Gaston County', countySlug: 'gaston-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-bessemer'], avgRoofCost: { low: 5500, mid: 9000, high: 14000 }, housingTypes: ['Ranch', 'Traditional', 'Mill houses'], avgHomeAge: '45-80 years', avgHomeValue: '$125,000 - $250,000', roofingNotes: 'Affordable Gaston County community with older housing stock.' },

  // ============================================
  // LINCOLNTON/LINCOLN COUNTY (4 zips)
  // ============================================
  { zipCode: '28092', cityName: 'Lincolnton', citySlug: 'lincolnton-nc', countyName: 'Lincoln County', countySlug: 'lincoln-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-lincolnton', 'lincoln-academy'], avgRoofCost: { low: 6500, mid: 10500, high: 16500 }, housingTypes: ['Historic', 'Ranch', 'Traditional'], avgHomeAge: '35-90 years', avgHomeValue: '$200,000 - $400,000', roofingNotes: 'Lincoln County seat with historic courthouse square and classic homes.' },
  { zipCode: '28037', cityName: 'Denver', citySlug: 'denver-nc', countyName: 'Lincoln County', countySlug: 'lincoln-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['lake-norman-area', 'westport'], avgRoofCost: { low: 8500, mid: 14000, high: 24000 }, housingTypes: ['Lakefront', 'Traditional', 'Custom'], avgHomeAge: '15-35 years', avgHomeValue: '$400,000 - $900,000', roofingNotes: 'Lake Norman west shore community with waterfront and golf course homes.' },

  // ============================================
  // STATESVILLE/IREDELL COUNTY (5 zips)
  // ============================================
  { zipCode: '28625', cityName: 'Statesville', citySlug: 'statesville-nc', countyName: 'Iredell County', countySlug: 'iredell-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-statesville', 'fourth-creek'], avgRoofCost: { low: 6500, mid: 10500, high: 16500 }, housingTypes: ['Historic', 'Ranch', 'Traditional'], avgHomeAge: '40-100 years', avgHomeValue: '$175,000 - $350,000', roofingNotes: 'Iredell County seat with historic downtown and Victorian homes.' },
  { zipCode: '28677', cityName: 'Statesville', citySlug: 'statesville-nc', countyName: 'Iredell County', countySlug: 'iredell-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['east-statesville', 'bethany-area'], avgRoofCost: { low: 7000, mid: 11000, high: 17500 }, housingTypes: ['Traditional', 'Ranch', 'New construction'], avgHomeAge: '25-50 years', avgHomeValue: '$225,000 - $425,000', roofingNotes: 'Growing east Statesville with newer subdivisions along I-40 corridor.' },
  { zipCode: '28166', cityName: 'Troutman', citySlug: 'troutman-nc', countyName: 'Iredell County', countySlug: 'iredell-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-troutman', 'esc-area'], avgRoofCost: { low: 6500, mid: 10500, high: 16500 }, housingTypes: ['Ranch', 'Traditional', 'Farmhouses'], avgHomeAge: '30-60 years', avgHomeValue: '$200,000 - $400,000', roofingNotes: 'Small town between Statesville and Mooresville with rural character.' },

  // ============================================
  // SALISBURY/ROWAN COUNTY (5 zips)
  // ============================================
  { zipCode: '28144', cityName: 'Salisbury', citySlug: 'salisbury-nc', countyName: 'Rowan County', countySlug: 'rowan-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-salisbury', 'fulton-heights'], avgRoofCost: { low: 6000, mid: 9500, high: 15000 }, housingTypes: ['Historic', 'Victorian', 'Ranch'], avgHomeAge: '50-150 years', avgHomeValue: '$150,000 - $350,000', roofingNotes: 'Historic downtown with Victorian architecture and older housing stock.' },
  { zipCode: '28146', cityName: 'Salisbury', citySlug: 'salisbury-nc', countyName: 'Rowan County', countySlug: 'rowan-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['east-salisbury', 'country-club'], avgRoofCost: { low: 6500, mid: 10500, high: 17000 }, housingTypes: ['Traditional', 'Ranch', 'Colonial'], avgHomeAge: '35-60 years', avgHomeValue: '$200,000 - $400,000', roofingNotes: 'East Salisbury with established neighborhoods and golf course community.' },
  { zipCode: '28147', cityName: 'Salisbury', citySlug: 'salisbury-nc', countyName: 'Rowan County', countySlug: 'rowan-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['west-salisbury', 'spencer-area'], avgRoofCost: { low: 5500, mid: 9000, high: 14500 }, housingTypes: ['Ranch', 'Traditional', 'Historic'], avgHomeAge: '45-80 years', avgHomeValue: '$125,000 - $275,000', roofingNotes: 'Working-class neighborhoods with affordable housing options.' },
  { zipCode: '28159', cityName: 'Spencer', citySlug: 'spencer-nc', countyName: 'Rowan County', countySlug: 'rowan-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-spencer', 'transportation-museum'], avgRoofCost: { low: 5500, mid: 9000, high: 14000 }, housingTypes: ['Historic', 'Ranch', 'Bungalows'], avgHomeAge: '60-120 years', avgHomeValue: '$100,000 - $225,000', roofingNotes: 'Historic railroad town with older homes and Transportation Museum.' },

  // ============================================
  // ALBEMARLE/STANLY COUNTY (3 zips)
  // ============================================
  { zipCode: '28001', cityName: 'Albemarle', citySlug: 'albemarle-nc', countyName: 'Stanly County', countySlug: 'stanly-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-albemarle', 'pfeiffer-area'], avgRoofCost: { low: 6000, mid: 9500, high: 15000 }, housingTypes: ['Historic', 'Ranch', 'Traditional'], avgHomeAge: '40-80 years', avgHomeValue: '$150,000 - $300,000', roofingNotes: 'Stanly County seat with historic downtown and Pfeiffer University nearby.' },
  { zipCode: '28127', cityName: 'New London', citySlug: 'new-london-nc', countyName: 'Stanly County', countySlug: 'stanly-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['new-london'], avgRoofCost: { low: 5500, mid: 9000, high: 14000 }, housingTypes: ['Ranch', 'Farmhouses', 'Traditional'], avgHomeAge: '40-70 years', avgHomeValue: '$125,000 - $250,000', roofingNotes: 'Small Stanly County community with rural character.' },

  // ============================================
  // ADDITIONAL NC METRO ZIPS
  // ============================================
  { zipCode: '28006', cityName: 'Alexis', citySlug: 'alexis-nc', countyName: 'Gaston County', countySlug: 'gaston-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['alexis'], avgRoofCost: { low: 5500, mid: 9000, high: 14000 }, housingTypes: ['Ranch', 'Farmhouses', 'Traditional'], avgHomeAge: '40-70 years', avgHomeValue: '$150,000 - $300,000', roofingNotes: 'Rural Gaston County with agricultural properties.' },
  { zipCode: '28080', cityName: 'Iron Station', citySlug: 'iron-station-nc', countyName: 'Lincoln County', countySlug: 'lincoln-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['iron-station', 'east-lincoln'], avgRoofCost: { low: 7000, mid: 11500, high: 18500 }, housingTypes: ['Traditional', 'Ranch', 'Farmhouses'], avgHomeAge: '25-50 years', avgHomeValue: '$275,000 - $500,000', roofingNotes: 'East Lincoln County with rural-suburban character.' },
  { zipCode: '28090', cityName: 'Kings Mountain', citySlug: 'kings-mountain-nc', countyName: 'Cleveland County', countySlug: 'cleveland-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-kings-mountain', 'battleground-area'], avgRoofCost: { low: 6000, mid: 9500, high: 15000 }, housingTypes: ['Ranch', 'Traditional', 'Historic'], avgHomeAge: '40-70 years', avgHomeValue: '$150,000 - $300,000', roofingNotes: 'Historic Revolutionary War town with affordable housing.' },
  { zipCode: '28150', cityName: 'Shelby', citySlug: 'shelby-nc', countyName: 'Cleveland County', countySlug: 'cleveland-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['downtown-shelby', 'uptown'], avgRoofCost: { low: 5500, mid: 9000, high: 14500 }, housingTypes: ['Historic', 'Ranch', 'Traditional'], avgHomeAge: '45-90 years', avgHomeValue: '$125,000 - $275,000', roofingNotes: 'Cleveland County seat with historic uptown district.' },
  { zipCode: '28152', cityName: 'Shelby', citySlug: 'shelby-nc', countyName: 'Cleveland County', countySlug: 'cleveland-county-nc', state: 'North Carolina', stateAbbr: 'NC', neighborhoods: ['east-shelby', 'country-club'], avgRoofCost: { low: 6000, mid: 10000, high: 16000 }, housingTypes: ['Traditional', 'Ranch', 'Colonial'], avgHomeAge: '35-60 years', avgHomeValue: '$175,000 - $350,000', roofingNotes: 'East Shelby with golf course community and newer developments.' },
];

// ============================================
// UTILITY FUNCTIONS
// ============================================

export function getZipCodeData(zipCode: string): ZipCodeData | undefined {
  return ncZipCodes.find(z => z.zipCode === zipCode);
}

export function getAllZipCodes(): string[] {
  return ncZipCodes.map(z => z.zipCode);
}

export function getZipCodesByCity(citySlug: string): ZipCodeData[] {
  return ncZipCodes.filter(z => z.citySlug === citySlug);
}

export function getZipCodesByCounty(countySlug: string): ZipCodeData[] {
  return ncZipCodes.filter(z => z.countySlug === countySlug);
}

export function getUniqueZipCodes(): ZipCodeData[] {
  const seen = new Set<string>();
  return ncZipCodes.filter(z => {
    if (seen.has(z.zipCode)) return false;
    seen.add(z.zipCode);
    return true;
  });
}

export function getZipCodeCount(): number {
  return getUniqueZipCodes().length;
}
